### DISCUSSION TITLE
HTTP Status 403 Forbidden when connecting to WebSocket

### DISCUSSION THREAD

**Discussion by rushmi0** [micronaut-projects/micronaut-core#10948] [Q&A]
unable to connect to WebSocket from outside (public internet). how to resolve this issue?

![Screenshot 2024-07-05 162035](https://github.com/micronaut-projects/micronaut-core/assets/120770468/ff20e47e-3217-440d-8b16-0cd93a930bad)

// application.toml
```toml
 [micronaut.server]
 cors.enabled = true
 cors.localhost-pass-through = true
 port = 6724
```
