### DISCUSSION TITLE
How to log the body request when performing http call ?

### DISCUSSION THREAD

**Discussion by scaturigo** [micronaut-projects/micronaut-core#11582] [Q&A]
I'm trying to debug an issue with an HTTP API. How can I log the exact request body being sent, including headers and any encoded data, so I can compare it to the expected format?

**Comment by graemerocher** [comment]
Set `micronaut.http.client.log-level=TRACE` in `application.properties` then add `<logger name="io.micronaut.http.client" level="TRACE" />` in `logback.xml` to see raw packets being sent

**Reply by scaturigo** [reply]
Thank you, @graemerocher, for this quick response. It works perfectly to trace a classical post, but I want to log the multpart form payload of my request.


When I perform a post with this body:

`MultipartBody body = MultipartBody.builder()
                    .addPart("form[label]","test")
                    .addPart("form[code]", "42"). build()`

I want to see something like that:

------boundary123
Content-Disposition: form-data; name="form[label]"

test
------boundary123
Content-Disposition: form-data; name="form[code]"

42
------boundary123


Is it possible ?

**Reply by graemerocher** [reply]
should work the same, is is the raw request data from Netty

**Comment by TatyOko28** [comment]
### Solution : Enable logging in application.yml (Quickest)

The simplest approach – enable Micronaut's HTTP client logging.

**application.yml:**
```yaml
micronaut:
  http:
    client:
      logging-level: TRACE
      logger-name: "io.micronaut.http.client"

# Alternative: More specific logging
logger:
  levels:
    io.micronaut.http.client: TRACE
    io.micronaut.http.client.netty: TRACE
    reactor.netty.http.client: DEBUG
```

**logback.xml (ensure TRACE is enabled):**
```xml
<configuration>
    <logger name="io.micronaut.http.client" level="TRACE"/>
    <logger name="io.micronaut.http.client.netty" level="TRACE"/>
    <logger name="reactor.netty.http.client" level="DEBUG"/>
    
    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
```

**Expected output:**
```
TRACE i.m.h.client.netty - Request: POST /api/endpoint
TRACE i.m.h.client.netty - Headers: Content-Type: application/json, Accept: application/json
TRACE i.m.h.client.netty - Body: {"name":"John","age":30}
```
