### DISCUSSION TITLE
Integration with Oracle DB

### DISCUSSION THREAD

**Discussion by aberinnj** [micronaut-projects/micronaut-core#11642] [Q&A]
Hi all,

Is it possible to integrate Micronaut with an Oracle Autonomous DB without the pre-made modules? I only want to use the dependency:
```xml
    <!-- Production JAR -->
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11-production</artifactId>
      <version>23.7.0.25.01</version>
      <type>pom</type>
    </dependency>
```

**Comment by graemerocher** [comment]
sure just declare your dependency and create the datasource manually

**Reply by aberinnj** [reply]
Thanks Graemer, is there anything to note when building with graalvm native image and this approach? I tried it last time and the oraclepki jar wasn't being found

**Comment by TatyOko28** [comment]
### Solution : Minimal setup with HikariCP (Recommended)

This is the cleanest approach – use Micronaut's JDBC + Hikari module with the Oracle driver.

**Dependencies (Maven):**
```xml
<dependencies>
    <!-- Micronaut JDBC with Hikari connection pool -->
    <dependency>
        <groupId>io.micronaut.sql</groupId>
        <artifactId>micronaut-jdbc-hikari</artifactId>
    </dependency>
    
    <!-- Plain Oracle JDBC driver -->
    <dependency>
        <groupId>com.oracle.database.jdbc</groupId>
        <artifactId>ojdbc11-production</artifactId>
        <version>23.7.0.25.01</version>
        <type>pom</type>
    </dependency>
    
    <!-- Optional: Micronaut Data or just plain JDBC -->
    <dependency>
        <groupId>io.micronaut.data</groupId>
        <artifactId>micronaut-data-jdbc</artifactId>
    </dependency>
    
    <!-- Optional: Connection validation -->
    <dependency>
        <groupId>com.oracle.database.security</groupId>
        <artifactId>oraclepki</artifactId>
        <version>23.7.0.25.01</version>
    </dependency>
    <dependency>
        <groupId>com.oracle.database.security</groupId>
        <artifactId>osdt_cert</artifactId>
        <version>23.7.0.25.01</version>
    </dependency>
    <dependency>
        <groupId>com.oracle.database.security</groupId>
        <artifactId>osdt_core</artifactId>
        <version>23.7.0.25.01</version>
    </dependency>
</dependencies>
```

**Gradle (Kotlin DSL):**
```kotlin
dependencies {
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("com.oracle.database.jdbc:ojdbc11-production:23.7.0.25.01")
    implementation("io.micronaut.data:micronaut-data-jdbc")
    
    // For SSL/wallet support (Autonomous DB)
    implementation("com.oracle.database.security:oraclepki:23.7.0.25.01")
    implementation("com.oracle.database.security:osdt_cert:23.7.0.25.01")
    implementation("com.oracle.database.security:osdt_core:23.7.0.25.01")
}
```

**Application.yml for Autonomous DB (with wallet):**
```yaml
micronaut:
  application:
    name: my-app

datasources:
  default:
    url: jdbc:oracle:thin:@<dbname>_low?TNS_ADMIN=/path/to/wallet
    driverClassName: oracle.jdbc.OracleDriver
    username: your_username
    password: your_password
    dialect: ORACLE
    pool:
      max-size: 20
      min-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    
    # Oracle-specific connection properties
    connection-properties:
      oracle.net.ssl_version: 1.2
      oracle.net.ssl_server_dn_match: true
```

**Application.yml for Autonomous DB (without wallet, using TLS):**
```yaml
datasources:
  default:
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.your-region.oraclecloud.com))(connect_data=(service_name=your_dbname_low))(security=(ssl_server_dn_match=yes)))
    driverClassName: oracle.jdbc.OracleDriver
    username: your_username
    password: your_password
```
