### DISCUSSION TITLE
Correct setup Gradle Project for Micronaut SourceGen

### DISCUSSION THREAD

**Discussion by outlndrr** [micronaut-projects/micronaut-core#11717] [Q&A] [answered]
Hi!

I'm trying to use Micronaut SourceGen to create my own source generator, but I'm not sure how to properly set up a Gradle project. I know it should be a separate module, but which dependencies and plugins should I use? There is no information I need in official documentation about this.

Versions:

- Micronaut: 4.8.0
- Micronaut SourceGen: 1.7.2

**Comment by graemerocher** [comment]
maybe you can checkout a subproject that uses it like the JSON schema module https://github.com/micronaut-projects/micronaut-json-schema

**Reply by outlndrr** [reply]
I've checked the repository and tried to create a similar project, but it didn't work. After running the "kaptKotlin" Gradle task, it won't start again due to an error that says the jar is being used by another process. I have two Gradle modules: "shared" with source generation, and "app" for the application. The code for the source generator was taken from the official documentation.

build.gradle.kts (shared module):
```kotlin
plugins {
    kotlin("jvm") version "1.9.25"
}

dependencies {
    compileOnly(mn.micronaut.core.processor)
    implementation(mnSourcegen.micronaut.sourcegen.model)
    implementation(mnSourcegen.micronaut.sourcegen.generator)
    implementation(mnSourcegen.micronaut.sourcegen.generator.kotlin)
    implementation(mnSourcegen.micronaut.sourcegen.annotations)
}
```

build.gradle.kts (app module):
```kotlin
// above default generated code from launcher
dependencies {
    kapt(project(":shared"))
    implementation(project(":shared"))

   // default generated micronaut dependecies
}
// below default generated code from launcher
```

libs.versions.toml
```toml
[versions]
micronaut = "4.8.9"
micronaut-sourcegen = "1.7.2"
kotlin = "1.9.25"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-sourcegen = { module = "io.micronaut.sourcegen:micronaut-sourcegen-bom", version.ref = "micronaut-sourcegen" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
```

settings.gradle.kts:
```kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("io.micronaut.build.shared.settings") version "7.3.2"
}

rootProject.name="sourgen-test"

include("shared")
include("app")

configure<io.micronaut.build.MicronautBuildSettingsExtension> {
    importMicronautCatalog()
    importMicronautCatalog("micronaut-sourcegen")
}
```
