### DISCUSSION TITLE
Configuring the response headers' maximum size for low-level Netty clients

### DISCUSSION THREAD

**Discussion by adamkobor** [micronaut-projects/micronaut-core#11777] [Q&A]
hey there, I'm having an issue with the low-level client (it might be that the declarative one is also affected, but I didn't try TBH), because some of my upstreams return a large header that won't fit into Netty's default, which is 8192 byte according to the exception I get:
```Error occurred reading HTTP response: Header size exceeded max allowed size (8192)```

I didn't find any clue about the possibility of overriding this default, not in Netty's own documentation and especially not in Micronaut's docs. Does anybody know if it would be somehow possible?

**Comment by TatyOko28** [comment]
## Cause

Netty's HTTP decoder has a default `maxHeaderSize` of **8192 bytes**. This limit applies to:
- Request headers (for server)
- Response headers (for client)

When an HTTP response header exceeds this limit, Netty throws a `TooLongFrameException` which Micronaut translates into the error message you're seeing.

### Solution : Configure via application.yml (Recommended)

For Micronaut's HTTP client, configure the `max-header-size` property.

**application.yml:**
```yaml
micronaut:
  http:
    client:
      max-header-size: 16384  # 16KB
      # Or larger, e.g., 32768 (32KB) or 65536 (64KB)
```

**Or for a specific client by ID:**
```yaml
micronaut:
  http:
    clients:
      my-client:
        max-header-size: 32768
        read-timeout: 30s
        connect-timeout: 10s
```

**Comment by lMysticl** [comment]
The global property in the previous comment is correct, but the named-client prefix is `micronaut.http.services`, not `micronaut.http.clients`.

For the default injected client:

```yaml
micronaut:
  http:
    client:
      max-header-size: 32768
```

For a named client such as `@Client("upstream")`:

```yaml
micronaut:
  http:
    services:
      upstream:
        max-header-size: 32768
```

Those prefixes come directly from [`DefaultHttpClientConfiguration`](https://github.com/micronaut-projects/micronaut-core/blob/5.1.x/http-client-core/src/main/java/io/micronaut/http/client/DefaultHttpClientConfiguration.java#L30-L39) and [`ServiceHttpClientConfiguration`](https://github.com/micronaut-projects/micronaut-core/blob/5.1.x/http-client-core/src/main/java/io/micronaut/http/client/ServiceHttpClientConfiguration.java#L39-L50). `max-header-size` maps to `HttpClientConfiguration.setMaxHeaderSize(int)` and applies to response headers handled by the client.

If “low-level client” means one created manually with `HttpClient.create(...)`, application YAML is not involved. Pass the configuration explicitly:

```java
DefaultHttpClientConfiguration configuration =
        new DefaultHttpClientConfiguration();
configuration.setMaxHeaderSize(32 * 1024);

try (HttpClient client = HttpClient.create(baseUrl, configuration)) {
    // use client
}
```

`micronaut.server.netty.max-header-size` is a different setting: it controls request headers accepted by the server, not response headers read by this client.
