### DISCUSSION TITLE
How to reuse class for multiple ConfigurationProperties in Kotlin

### DISCUSSION THREAD

**Discussion by LegoRocks** [micronaut-projects/micronaut-core#11804] [Q&A]
In my Kotlin application, I have a set of feature flags. However these flags are not globally set but may different for certain business and functions and should be configured using the `application.yml`. My yml looks something like this:

```yaml
app:
  flags:
    function1:
      flag1: true
      flag2: false
      flag3: true
    function2:
      flag1: false
      flag2: true
      flag3: false
    function3:
      flag1: false
      flag2: false
      flag3: false
```

I want to bind them using `@ConfigurationProperties` and built the following:
```kotlin
@ConfigurationProperties("app.flags")
class FeatureFlagSettings {
   var function1: FeatureFlagProperties
   var function2: FeatureFlagProperties
   var function3: FeatureFlagProperties
}

class FeatureFlagProperties {
   var flag1: Boolean
   var flag2: Boolean
   var flag3: Boolean
}
```

But I quickly realized, that the properties are not properly set. Apparently this is way of building properties only works for Java but not Kotlin. Of course I could simply copy and paste the `FeatureFlagProperties` class for each function with it's own class name and `@ConfigurationProperties` but that seems not like the proper way of doing things.

Is there a way to use `@ConfigurationProperties` and reuse a class with reocurring properties? I know there is the `@EachProperty` annotation but my use case is for predefined properties, not a generic collection of entries.
