### DISCUSSION TITLE
Externalize application.yml file using Kubernetes ConfigMaps

### DISCUSSION THREAD

**Discussion by darrenSchlager** [micronaut-projects/micronaut-core#3942] [Q&A] [answered]
I am new to Micronaut and am trying to figure out how to externalize a services application.yml file using Kubernetes ConfigMaps. So far I have added a bootstrap.yml file that is setup as shown here:
https://micronaut-projects.github.io/micronaut-kubernetes/1.1.0/guide/index.html#config-client
I also have setup a ConfigMap called config that contains the key retrieve-service.yml and the value is the file contents. I created the config map using:
"kubectl create configmap config --from-file=retrieve-service.yml"
When I check the logs I am seeing:
"i.m.d.c.c.DistributedPropertySourceLocator - Resolved 0 configuration sources from client: compositeConfigurationClient()"

Here is my bootstrap.yml:
```yaml
---
micronaut:
  application:
    name: retrieve-service
  config-client:
    enabled: true
---
kubernetes:
  client:
    config-maps:
      includes:
        - config
```
In my build.gradle I have:
```groovy
...
dependencies {
...
    implementation "io.micronaut.kubernetes:micronaut-kubernetes-discovery-client:1.1.0"
...
```
