### DISCUSSION TITLE
Native Image: Management API on different port does not work

### DISCUSSION THREAD

**Discussion by saw303** [micronaut-projects/micronaut-core#8051] [Q&A]
In my Micronaut application I expose the Management endpoints on a different port. The reason for this is that the API is not unknowingly available via a reverse proxy.

```yml
endpoints:
  all:
    port: 8090
    path: /endpoints
  health:
    enabled: true
    sensitive: false
```

When I run the Micronaut application as a fatjar, everything works as expected. But when I run the native image, it seems that Netty is not listening on that port.

```sh
/ # http localhost:8090/endpoints/health

http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /endpoints/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8572fd9c70>: Failed to establish a new connection: [Errno 111] Connection refused')) while doing a GET request to URL: http://localhost:8090/endpoints/health
```

Is this the separate port not supported in the native image or am I missing something?
