### DISCUSSION TITLE
CSP settings do not work

### DISCUSSION THREAD

**Discussion by AdiWehrli** [micronaut-projects/micronaut-core#8337] [Q&A]
Hello together,

I use AKHQ von @tchiotludo which is based on micronaut's version 3.6.3. As documented I added the following configuration in `application.yml` file:
```yaml
micronaut:
  application:
    name: akhq
  security:
  .
  .
  .
  views:
    enabled: true
    csp:
      enabled: true
      policyDirectives: "default-src 'none'; frame-src 'self'; script-src 'nonce-{#nonceValue}' 'self'; connect-src 'self'; img-src 'self' data:; style-src 'nonce-{#nonceValue}' 'self'; frame-ancestors 'self'; form-action 'self'; font-src 'self'; manifest-src 'self'; worker-src blob:; upgrade-insecure-requests"
      generateNonce: true
```
After restart with this configuration there is no sign of any CSP response header (in browser's dev tools).

What am I doing wrong?

Thanks very much in advance.

Kind regards,
Adi
