### DISCUSSION TITLE
How to read secrets from AWS Secret Manager at a specific path

### DISCUSSION THREAD

**Discussion by srasane-hbo** [micronaut-projects/micronaut-core#8458] [Q&A]
I have secrets store at a specific path such as `/secrets/myApp/` on AWS secret manager.
I referred this [guide](https://guides.micronaut.io/latest/micronaut-aws-secretsmanager-gradle-java.html) and used micronaut’s secret manager dependency,
 
         <dependency>
            <groupId>io.micronaut.aws</groupId>
            <artifactId>micronaut-aws-secretsmanager</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.aws</groupId>
            <artifactId>micronaut-aws-sdk-v2</artifactId>
            <version>3.9.2</version>
            <scope>compile</scope>
        </dependency>

I have config-client enabled in bootstrap.yml

From the logs, its trying to read secrets from /config/

`{"@timestamp":"2022-12-01T23:41:30.057Z","message":"zero secrets for prefix: /config/myApp/","class":"io.micronaut.aws.secretsmanager.SecretsManagerKeyValueFetcher","thread":"main","trace":"TRACE"}`

Based on this, https://micronaut-projects.github.io/micronaut-aws/latest/guide/configurationreference.html#io.micronaut.aws.distributedconfiguration.AwsDistributedConfigurationProperties , it seems like the custom prefix cannot to be set, is there a way to read secrets from a specific path?

**Comment by graemerocher** [comment]
https://github.com/micronaut-projects/micronaut-aws/pull/1481 might help

**Reply by srasane-hbo** [reply]
Thanks for replying.
According to this [document](https://github.com/micronaut-projects/micronaut-aws/blob/b41e83ce96bdb31e3d14aa79b9050195cba210df/src/main/docs/guide/distributedconfiguration/distributedconfigurationsecretsmanager.adoc)   it seems like the `/config/` still gets appended to the path, is there a way to avoid that.

I was able to use just following config to resolve one secret,
```
aws:
  distributed-configuration:
    prefix: "database/service/merchandising-apis/content-promotion/dev/beam-amer/aurorapostgres/v1/ro"
    search-active-environments: false
    common-application-name: ""
    delimiter: ""
```
 but this doesn't work for multiple secrets.
From the code it seems like the AWSDistributionConfiguration is invoked [here](https://github.com/micronaut-projects/micronaut-aws/blob/87144fe88eff3642a0c4a75f7b854469c0c2fae8/aws-secretsmanager/src/main/java/io/micronaut/aws/secretsmanager/SecretsManagerConfigurationClient.java#L70) which sets the default prefix as `/config/`, so i tried the following  but it didnt work

``` 
aws:
  distributed-configuration:
    search-active-environments: false
    common-application-name: ""
    prefix: ""
    delimiter: ""
  secretsmanager:
    enabled: true
    secrets:
      - secret-name: "secrets/myApp/dbSecret"
        prefix: "db"
      - secret-name: "secrets/kafkaSecret"
        prefix: "kafka"
```
Is there a way to disable `distributed-configuration`? And what does the prefix under secretManager indicate?
Update: v3.9.3 does not seem to have [secrets config](https://github.com/micronaut-projects/micronaut-aws/blob/v3.9.3/aws-secretsmanager/src/main/java/io/micronaut/aws/secretsmanager/SecretsManagerConfigurationProperties.java). Do you know when would it be released?
