### DISCUSSION TITLE
Health Indicators for micronaut.http.services.*

### DISCUSSION THREAD

**Discussion by alexsimpson440dev** [micronaut-projects/micronaut-core#8855] [Ideas]
Potentially a question or an idea, but when setting up and testing a service in micronaut under the configuration:
```
micronaut:
  http:
    services:
      foo:
        url: some-url
        health-check: true
        health-check-interval: 15s
        health-check-uri: /health
```

I didn't really notice any difference when our health endpoint would return an error such as a 404, 401, 500, etc. After looking into Micronauts [code](https://github.com/micronaut-projects/micronaut-core/blob/0f3420933debfde31a6cf64d781ee7469d318415/http-client-core/src/main/java/io/micronaut/http/client/ServiceHttpClientFactory.java#L93) and documentation I noticed that this health seems to only remove a single URL from the load balancer if an endpoint returns as unhealthy.

Potentially I am missing a way to tie this to a health indicator through configuration, but if not I think that would be a nice feature.

So a potential response from the health aggregation endpoint would be:
![image](https://user-images.githubusercontent.com/22035731/221994275-0ed0158f-7df5-4070-ae02-acd6239c0d52.png)

Maybe when all urls of a given service are down (foo in this example):
![image](https://user-images.githubusercontent.com/22035731/221994705-2de44bf2-9d7e-4bb3-99dc-e3bc10b813a8.png)

Documentation I am using: 
- https://docs.micronaut.io/latest/guide/index.html#serviceDiscoveryManual
- https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.client.ServiceHttpClientConfiguration
