### DISCUSSION TITLE
Is there a way to make Micronaut Serialization not accept floats as integers when deserializing?

### DISCUSSION THREAD

**Discussion by runenielsen** [micronaut-projects/micronaut-core#9697] [Q&A] [answered]
Is there a way to make Micronaut Serialization not accept floats as integers when deserializing?

I want to achieve the same as this configuration achieve for Jackson:

```
jackson:
  deserialization:
    accept-float-as-int: false             <--- THIS
    fail-on-unknown-properties: true
```

I couldn't find anything in the documentation...

I am asking here, since there are no discussions in the Micronaut Serialization repository.

I found by browsing the code, that the other Jackson configuration (fail on unknown properties) can be achieved for Serde like this:

```
micronaut:
  serde:
    deserialization:
      ignore-unknown: false
```
