### DISCUSSION TITLE
Is it possible to change swagger ui to http://localhost:8080/openapi instead of /swagger/views/swagger-ui

### DISCUSSION THREAD

**Discussion by subash89** [micronaut-projects/micronaut-core#9987] [Q&A] [answered]
I tried following like router config to get swagger ui at /openapi. But UI does not work. And when I build it, in target folder, it's always the META-INF/swagger/views/swagger-ui getting created. looks like this swagger/views/swagger-ui  path is hard coded somewhere?

```
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /openapi/**
```
