### ISSUE TITLE
/prometheus returns 401 with application.yml but works with application.properties

### ISSUE THREAD

**Issue by zoltan-toth-mw** [micronaut-projects/micronaut-core#10151]
### Expected Behavior

Prometheus metrics are available at /prometheus with this yaml config.

```yaml
endpoints:
  prometheus:
    sensitive: false
  metrics:
    enabled: true
    export:
      prometheus:
        descriptions: true
        enabled: true
        step: PT1M
```

### Actual Behaviour

/prometheus endpoint returns with 401.

However if I replace the application.yml with application.properties, it works.

```properties
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.step=PT1M
micronaut.metrics.export.prometheus.descriptions=true
endpoints.prometheus.sensitive=false
```

Also note that, with the yml config, the environment.all.path setting also doesn't work.

### Steps To Reproduce

Create a project with micronaut cli 4.2
```
What type of application do you want to create? (enter for default)
*1) Micronaut Application
 2) Micronaut CLI Application
 3) Micronaut Serverless Function
 4) Micronaut gRPC Application
 5) Micronaut Messaging Application
> 1

Choose your preferred language. (enter for default)
*1) Java
 2) Groovy
 3) Kotlin
> 3

Choose your preferred test framework. (enter for default)
*1) JUnit
 2) Spock
 3) Kotest
> 1

Choose your preferred build tool. (enter for default)
 1) Gradle (Groovy)
*2) Gradle (Kotlin)
 3) Maven
> 1

Choose the target JDK. (enter for default)
*1) 17
 2) 21
> 1

Enter any features to apply. Use tab for autocomplete and separate by a space.
> micrometer-prometheus management 

Enter a name for the project.
> prometheus2
```

Update the application.properties file with:
```
micronaut.application.name=prometheus2
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.step=PT1M
micronaut.metrics.export.prometheus.descriptions=true
endpoints.prometheus.sensitive=false
#endpoints.all.path=/app/
```
For `curl -v localhost:8080/prometheus` a proper prometheus response will be shown.

Now replace application.properties with application.yml that has the same content but in yaml format:

```yaml
endpoints:
  prometheus:
    sensitive: false
#  all:
#    path: /app/
micronaut:
  application:
    name: prometheus2
  metrics:
    enabled: true
    export:
      prometheus:
        descriptions: true
        enabled: true
        step: PT1M
```

For `curl -v localhost:8080/prometheus` an empty response will be shown with 401 status code.

### Environment Information

macOs Ventura 13.2
Oracle OpenJdk 17.0.2

### Version

4.2.0
