### ISSUE TITLE
 Issue with Response Body Conversion after Upgrading to 4.2.1

### ISSUE THREAD

**Issue by RajeevMasseyTR** [micronaut-projects/micronaut-core#10296]
### Issue description

**Description**
After upgrading our application to version 4.2.1, we are experiencing an issue where the response body is not being converted correctly. Previously, the application was working perfectly, but post-migration, the response body conversion to the desired type is failing.

**Environment**

- Version: 4.2.1
- Language: Java 17

**Expected Behavior**
The response body should be converted to the specified target type as it was in the previous version.

**Actual Behavior**
The conversion of the response body to the specified target type is failing, and the application logs show the following trace message: "Unable to convert response body to target type class [TargetType]"

**Logs**
Here are the relevant logs (sensitive information has been redacted for security):

```
[DATE/TIME] INFO  [Thread] [Logger] - Intercepted for auth setup
[DATE/TIME] DEBUG [Thread] [Logger] - Sending HTTP POST to [Endpoint]
[...]
[DATE/TIME] TRACE [Thread] [Logger] - Response Body
[DATE/TIME] TRACE [Thread] [Logger] - ----
[DATE/TIME] TRACE [Thread] [Logger] - {"message":"Success","accountId":"[REDACTED]","accNumber":"[REDACTED]"}
[DATE/TIME] TRACE [Thread] [Logger] - ----
[DATE/TIME] TRACE [Thread] [Logger] - Unable to convert response body to target type class [TargetType]
[...]
```

appliation.yml

```
micronaut:
  application:
    name: [REDACTED]
  netty:
    event-loops:
      http-client-group:
        num-threads: 10
        prefer-native-transport: true
  codec:
    json:
      additionalTypes:
        - application/octet-stream
  http:
    client:
      event-loop-group: http-client-group
      read-timeout: 20s
      connect-timeout: 8s
```

Client Interface with method 

 ```
   @Post("/services/v1/createAccoutn")
    HttpResponse<AccountCreatedResponse> createAccount(@Body AccountCreatedRequest request);
```

AccountCreatedResponse 

```
@Data
@RequiredArgsConstructor
public class AccountCreatedResponse {
    public static final String NOT_FOUND = "not found";
    private String message;
    @JsonProperty("accountId")
    private String crmId;
    @JsonProperty("accNumber")
    private String accountNumber;

    public boolean isContactNotFoundError() {
        return NOT_FOUND .equalsIgnoreCase(message);
    }
}
```

    
**Additional Information**

- The issue started occurring immediately after upgrading to version 4.2.1.
- The content appear correctly in the unpooledContent byte array.
- Also tried using @Produces and @Consumes to MediaType.APPLICATION_JSON but it didn't work
