### ISSUE TITLE
HealthEndpoint details not visible when set to AUTHENTICATED but micronaut-security is disabled

### ISSUE THREAD

**Issue by desmondblue** [micronaut-projects/micronaut-core#10378]
### Expected Behavior

The health endpoint details visibility inherits from micronaut security in case of AUTHENTICATED access. If security is disabled it should behave like ANONYMOUS otherwise as is

### Actual Behaviour

The health endpoint details are not visible

### Steps To Reproduce

Steps to reproduce
1. Create an application.yml with the following content:
```
micronaut:
  application:
    name: my-app
    security: ${SECURITY_ENABLED:false}

endpoints:
  health:
    enabled: true
    sensitive: ${micronaut.security.enabled}
    details-visible: AUTHENTICATED
```
2. Add compile "io.micronaut:micronaut-management" to build.gradle

The application is set to work in two cases with micronaut-security being enabled and also while being disabled.
Now upon setting the details-visible property of HealthEndpoint as AUTHENTICATED. I expected that the property inherits from micronaut-security and shall show details to all users if the security is disabled. Wherein if the security is enabled then the details should only be visible to authenticated users. Please correct me if my understanding is wrong in this case or whether this is a plausible bug

### Environment Information

-OS: Windows
-Java11

### Version

3.10.3
