### ISSUE TITLE
Improvement - Create load balancer discovery client from static server list

### ISSUE THREAD

**Issue by hberrayana** [micronaut-projects/micronaut-core#1040]
This is an enhancement that replies to the use case where we might statically configure multiple URLs for the same service and we wish to perform Round Robin and Circuit breaking from that list.

I looked in the documentation and sources and found that load balancing (Ribbon or Round robin) can only be used using `@Client` annotation through `HttpClientIntroductionAdvice`
Configuration sample:
```
micronaut:
    http:
        services:
            profile:
                urls:
                    - http://172.16.100.85:8181/profile
                    - http://172.16.100.86:8181/profile
```
My issue with `@Client` is that I can't predict the number of clients that we can deal with in the code. I need to have an array of RxHttpClient instances each able to load balance and to have circuit breaking.
