### ISSUE TITLE
GORM error on startup

### ISSUE THREAD

**Issue by ross-oreto** [micronaut-projects/micronaut-core#1047]
### Steps to Reproduce

1. mn create-app micro --features hibernate-gorm,groovy,spock
2. cd micro
3. create gorm entity in micro package
```
package micro

import grails.gorm.annotation.Entity
import org.grails.datastore.gorm.GormEntity

@Entity
class Person implements GormEntity<Person> {
    String firstName
    String lastName
}
```
4. gradlew run

### Expected Behaviour

Application should start on localhost

### Actual Behaviour

Error occurs:
 ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.grails.orm.hibernate.HibernateDatastore] could not be loaded: Error instantiating bean of type [org.grails.orm.hibernate.HibernateDatastore]: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.grails.orm.hibernate.HibernateDatastore] could not be loaded: Error instantiating bean of type [org.grails.orm.hibernate.HibernateDatastore]: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.0.2
- **JDK Version:** jdk1.8.0_181

**Comment by Ashley-Belka** [comment]
I'm getting the same error. Switching back to 1.0.1 worked.

**Comment by graemerocher** [comment]
The reason for this is GORM configuration wasn't working correctly previously and the default config includes configuration for the second level cache to use Hibernate Ehcache. To resolve the issue you can either add the `hibernate-ehcache` dependency:

```groovy
runtime "org.hibernate:hibernate-ehcache:5.1.9.Final"
```

Or comment out the region cache configuration in the generated `application.yml`:

```yaml
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
   # remove this line
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
```
