### ISSUE TITLE
Healthcheck Endpoint Unauthorized

### ISSUE THREAD

**Issue by emazzotta** [micronaut-projects/micronaut-core#1108]
### Steps to Reproduce

1. Create an `application.yml` with the following content:

```
micronaut:
  application:
    name: my-app

endpoints:
  health:
    enabled: true
    sensitive: true
    details-visible: ANONYMOUS
```

2. Add `compile "io.micronaut:micronaut-management"` to `build.gradle`

### Expected Behaviour

The app provides a health check endpoint at http://localhost:8080/health without the need to authorize.

### Actual Behaviour

The app provides a health check endpoint at http://localhost:8080/health but immediately returns status code 401 Unathorized.

### Environment Information

- **Operating System**: macOS Mojave 10.14.2 (18C54)
- **Micronaut Version:** io.micronaut:micronaut-bom:1.0.1
- **JDK Version:** openjdk version "11" 2018-09-25

Is this a bug or is this expected behaviour? Am I missing something?
