### ISSUE TITLE
Lets Encrypt Integration

### ISSUE THREAD

**Issue by hc-codersatlas** [micronaut-projects/micronaut-core#1117]
Hi, the SSL documentation mentions Let's Encrypt, but doesn't integrate with the Java ACME client. It'd be good to have this integrated and the certificates auto-generated / renewed (as a background task). Thanks!

**Comment by zendern** [comment]
I'm considering picking this but wanted to at least write out what Im thinking on how to get there and get some feedback to make sure I'm on the right path.

### Changes needed

1. Setup daily?? background task `@Scheduled(fixedRate = "24h")`, probably configurable?? to check if the cert is valid. Probably also want this to happen on initial startup (in the background of course to not impact startup time) since if no lets encrypt certificate is there you dont want to wait 24h before the application is using valid ssl setup.
2. If cert is within a 30 days or less of renewal (maybe configurable renewal time??, default 30days to match certbot renewal time https://certbot.eff.org/docs/using.html#renewing-certificates), use acme4j to do the renewal (https://shredzone.org/maven/acme4j/usage/order.html)
3. Once we have the cert we will "refresh" the `SSLContext` for the `NettyHttpServer` so have it now use the new cert. Also once we have the new cert we will save it to disk. `micronaut.ssl.letsEncrypt.certPath`
   1. Which means we will need to define a custom `SSLContext` in this class so that the keystore can be refreshed when we have a new cert. Just like how a custom `SSLContext` is being done for the self signed certificate path. https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/NettyServerSslBuilder.java#L64
4. Add a new endpoint so that LetsEncrypt can validate the domain with the path of `/.well-known/acme-challenge/{token}`. (https://shredzone.org/maven/acme4j/challenge/http-01.html) This would be marked with `defaultEnabled=true` and `defaultSensitive=false` since let's encrypt needs to call into it.


### Sample Config
Thinking the configuration would live under `micronaut.ssl` and would probably look something like this.

```
micronaut:
    ssl:
        enabled: true
        letsEncrypt: 
        	enabled: true
        	certPath: <location cert should be saved to on disk>
        	keyPair: <xxxx>
        	renewWithin: 30 //number of days 
        	checkFrequency: 24 //hours/cron/etc (whatever @Scheduled allows)
        	createNewAccount: true //default false
        	accountEmail: contact@me.com //only needed for new account creation, default empty
        	agreeToTOS: true //only needed for new account creation, thought is its more of an explict thing to make sure you in fact agree, default false
        	domains: 
        		- <domain name>
        		- <domain name>
        		- ....
    		 ips: 
		   	- <ip>
		   	- <ip>
		   	- ...
        		
```

### Code location
Code will probably also get placed under the `io.micronaut.ssl` package under a `letsencrypt` package.

### Other thoughts on things that could be useful: 

1. `/cert/revoke` POST endpoint that you could call manually to revoke a certificate and pass a reason (https://shredzone.org/maven/acme4j/usage/certificate.html#Revocation). This would be marked with `defaultSensitive=true` and `defaultEnabled=false`
2. `/cert/renew` GET endpoint that you could call manually to get a new certificate outside of the background process. This would be marked with `defaultSensitive=true` and `defaultEnabled=false`
 


Any thoughts or suggestions on the above @hc-codersatlas @graemerocher ??
