### ISSUE TITLE
Why I need `snakeyaml` in classpath, if I already use AOT?

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#11391]
### Issue description

Imagine you have a typical microsoft project using openapi . You will have something like this configuration:
```yaml
micronaut:
  application:
    name: openapi-micronaut
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```

You also use AOT for optimization, with something like this configuration in the gradle:
```groovy
micronaut {
    version ver.micronaut
    runtime "netty"
    testRuntime "junit5"
    enableNativeImage false
    aot {
        optimizeServiceLoading = true
        convertYamlToJava = true
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
    }
}
```

With snakeyaml in classpath I see, that AOT created class with my properties:
```java
@Generated
public class ApplicationStaticPropertySource extends MapPropertySource {
    ApplicationStaticPropertySource() {
        super("application", new HashMap() {
            {
                this.put("micronaut.application.name", "openapi-micronaut");
                this.put("micronaut.server.port", 8080);
                this.put("micronaut.router.static-resources.swagger.paths", "classpath:META-INF/swagger");
                this.put("micronaut.router.static-resources.swagger.mapping", "/swagger/**");
                this.put("micronaut.router.static-resources.swagger-ui.paths", "classpath:META-INF/swagger/views/swagger-ui");
                this.put("micronaut.router.static-resources.swagger-ui.mapping", "/swagger-ui/**");
                this.put("micronaut.http.services.local.url", "http://127.0.0.1:8080");
                this.put("micronaut.http.services.test.url", "http://127.0.0.1:8080");
            }
        });
    }

    public int getOrder() {
        return Integer.MIN_VALUE;
    }
}
```

But if I remove snakeyaml from classpath, this class is not created.

So, the question is: why do I need snakeyaml in classpath if I use AOT precisely to get rid of it and do all the work at the compilation stage?
