### ISSUE TITLE
Allow specifying controller parameter value on conversion error

### ISSUE THREAD

**Issue by TbirdDuncan** [micronaut-projects/micronaut-core#11429]
### Expected Behavior

Found during migration from micronaut 3.x.x to 4.x.x. Before hand the config wasn't even needed to ignore enums that were unknown.
The following config: 
```
jackson:
  serialization-inclusion: NON_NULL
  deserialization:
    READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    ```
should make it so that unknown enum values in a request come back as null

### Actual Behaviour

io.micronaut.core.convert.exceptions.ConversionErrorException: Failed to convert argument [<arg>] for value [<value>] due to: No enum constant <enum.value>
	at io.micronaut.web.router.AbstractRouteMatch.failOnConversionErrors(AbstractRouteMatch.java:419)

### Steps To Reproduce

Make a micronaut app
create a get controller which utilizes @QueryValue and takes an enum as a dto 
send request with something not related to enum

### Environment Information

Mac: Sonoma 14.7 (23H124)
jdk 21

### Version

4.5.1
