### ISSUE TITLE
Micronaut mTLS with Self-Signed Certificate Without CA - Getting Unauthorized (401), but Works in Postman & Terminal

### ISSUE THREAD

**Issue by Vibhanshu3** [micronaut-projects/micronaut-core#11633]
### Expected Behavior

1. The Micronaut HTTP client should send the client certificate correctly.
2. The request should not be rejected with 401 Unauthorized.
3. Since Postman & curl work fine, Micronaut should behave the same way.

### Actual Behaviour

I am trying to configure Micronaut HTTP Client to communicate with a self-signed HTTPS server using mutual TLS (mTLS).

The server does not use a CA certificate, and I have set up client keystore and truststore as per the [Micronaut documentation](https://guides.micronaut.io/latest/micronaut-security-x509-maven-groovy.html) in which skipped the root CA cert.

However, I am still receiving a 401 Unauthorized error when making requests.

mTLS communication works fine in Postman & Terminal (curl). Fails with 401 Unauthorized in Micronaut HTTP Client.

**application.yml (For Client)**:

```
micronaut:
  http:
    client:
      ssl:
        enabled: true
        key-store:
          path: classpath:certs/client.p12
          password: changeit
          type: PKCS12
        trust-store:
          path: classpath:certs/truststore.jks
          password: changeit
          type: JKS

```

### Environment Information

- JDK Version: 17

### Version

3.9.6
