### ISSUE TITLE
Prometheus metrics registry configuration is not respected

### ISSUE THREAD

**Issue by archerizer** [micronaut-projects/micronaut-core#1172]
### Description

With the following configuration for Prometheus metrics registry:

```yml
micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT30S
        descriptions: false
```

The `false` value for `descriptions` is not respected.

### Expected Behaviour

`PrometheusMeterRegistry.scrape()` should return metrics in Prometheus format without commented descriptions such as: `# TYPE jvm_classes_loaded gauge`.

### Actual Behaviour

`PrometheusMeterRegistry.scrape()` returns commented descriptions regardless of the configuration value for `micronaut.metrics.export.prometheus.descriptions`.

### Environment Information

- **Operating System**: All
- **Micronaut Version:** 1.0.3
- **JDK Version:** OpenJDK 11
