### ISSUE TITLE
Ask a question, how does EntityManager switch data sources when multi-tenant?

### ISSUE THREAD

**Issue by tandi960505** [micronaut-projects/micronaut-core#1318]
【application.yml】
``` yaml
datasources:
    tenant1:
        url: jdbc:mysql://192.168.1.102:3306/micronaut?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: My@123456
        driverClassName: com.mysql.cj.jdbc.Driver
    tenant2:
        url: jdbc:mysql://127.0.0.1:3306/micronaut?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=true
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
jpa:
    tenant1:
        packages-to-scan:
            - 'multitenancy.catalogue.domain'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                show_sql: true
                format_sql: true
    tenant2:
        packages-to-scan:
            - 'multitenancy.catalogue.domain'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                hbm2ddl:
                    auto: update
                show_sql: true
                format_sql: true
```

【controller】
``` java
@Slf4j
@Controller("/client")
public class ClientController {

    @PersistenceContext
    @CurrentSession
    private EntityManager entityManager;

    @Inject
    HttpHeaderTenantResolver resolveTenantIdentifier;

    @Transactional(readOnly = true)
    @Get("/multitenancy")
    public String multitenancy(HttpRequest request) {
        /* 多租户处理 HttpHeaderTenantResolver*/
        // 方法1
//        String tenantId = request.getHeaders().get("tenantId");
//        log.info("当前请求的租户是: {}", tenantId);

        // 方法2
        String tenantId = (String)resolveTenantIdentifier.resolveTenantIdentifier();
        log.info("当前请求的租户是: {}", tenantId);

        List<Person> select_p_from_person_p = entityManager.createQuery("select p from Person p", Person.class).getResultList();
        log.info("select_p_from_person_p = {}", select_p_from_person_p);

        return tenantId;
    }

    @Get("/check")
    public String check(){
        return "ok";
    }
}

```
