### ISSUE TITLE
Static content is not loaded on first Web Application uberJar run

### ISSUE THREAD

**Issue by bHacklv** [micronaut-projects/micronaut-core#1372]
Hi!

I've experienced a very weird bug - after creating a shadowJar with "com.github.johnrengelman.shadow" plugin and running it - some static content is not loaded on the first web page load.
After 1 (sometimes 2) page refresh, they all finally get loaded. I can see some exceptions in the server logs. It happens both on MacOS and Windows.

Here is a screenshot from *Chrome dev tools - Network with 500 error* :
<img width="1489" alt="Screenshot 2019-03-13 at 23 50 15" src="https://user-images.githubusercontent.com/5772920/54317283-64a9ee00-45eb-11e9-8019-e6bcf9cd9180.png">

Here is a screenshot from *Chrome dev tools - Network after page refresh* :
<img width="1579" alt="Screenshot 2019-03-14 at 00 02 43" src="https://user-images.githubusercontent.com/5772920/54317710-9c656580-45ec-11e9-834e-bd4fd5971c26.png">

This is the *stack trace*:
[stacktrace.log](https://github.com/micronaut-projects/micronaut-core/files/2963852/stacktrace.log)

And this is router config that I have:

```
micronaut:
  router:
    static-resources:
      webjars:
        enabled: true
        paths: classpath:META-INF/resources/webjars
        mapping: /webjars/**
      public:
        enabled: true
        paths: classpath:public
        mapping: /public/**
```

### Steps to Reproduce

1. Package application as uberJar.
2. Run uberJar.
3. Open web application in browser.

### Expected Behaviour

Static content is not loaded on the first page load.

### Actual Behaviour

Static content is not loaded on the first page load.

### Environment Information

- **Operating System**: MacOS / Windows 7/10
- **Micronaut Version:** 1.1.0.M2
- **JDK Version:** 1.8.0_192
