### ISSUE TITLE
@Cacheable usage?

### ISSUE THREAD

**Issue by hampsterx** [micronaut-projects/micronaut-core#1373]
apologies this is almost certainly user error (background in python!) but cannot fathom how to get the caching to work :(

### Steps to Reproduce

```
micronaut:
    application:
        name: test
    caches:
        app:
            expire-after-access: 15m
            expire-after-write: 15m

```

```
@Cacheable("app")
fun getCacheTest() : String {
    println("not cached")
    return "test"
}
```

### Expected Behaviour

Expecting call that twice will cache the second invocation

### Actual Behaviour

Does not :(

### Environment Information

- **Micronaut Version: 1.04

Is there some missing configuration or something, I don't get any error about caching not set up or anything. sigh
