### ISSUE TITLE
OpenAPI Kotlin nullable

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1455]
In OpenAPI there is information about nullability
https://swagger.io/docs/specification/data-models/data-types/#null

But this info is not generated for 
```
class Greeting @JsonCreator constructor(
        @JsonProperty("id") val id: Long,
        @JsonProperty("content") val content: String,
        val temp: String?) {

}
```
```
components:
  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        temp:
          type: string
```

**Comment by puneetbehl** [comment]
@raderio This seems to be already fixed, please see the following Sample Application:

https://github.com/puneetbehl/openapi-kotlin-nullable

The above correctly generated the OpenAPI schema with `nullable: true` attribute on `temp` property as:

```yaml

  schemas:
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        temp:
          type: string
          nullable: true
```
