### ISSUE TITLE
InterceptUrlMapRule: Configuration Matching Bug

### ISSUE THREAD

**Issue by emazzotta** [micronaut-projects/micronaut-core#1511]
### Steps to Reproduce

1. Enable the security feature
```
# build.gradle
dependencies {
    annotationProcessor "io.micronaut:micronaut-security"
    implementation "io.micronaut:micronaut-security"
    ...
}
```

```
# application.yml
micronaut:
  security:
    enabled: true
```

2. Add an `intercept-url-map` in the app config for a specific route with a different behaviour depending on the `httpMethod`

```
# application.yml
micronaut:
  security:
    enabled: true
    intercept-url-map:
      - pattern: /v1/sessions/**
        access:
          - isAuthenticated()
      - pattern: /v1/sessions/**
        httpMethod: OPTIONS
        access:
          - isAnonymous()
```

### Expected Behaviour

`GET /v1/sessions/ABC` needs authentication
`POST /v1/sessions/` needs authentication
`PUT /v1/sessions/ABC` needs authentication
`OPTIONS /v1/sessions/` needs NO authentication

### Actual Behaviour

`GET /v1/sessions/ABC` needs authentication
`POST /v1/sessions/` needs authentication
`PUT /v1/sessions/ABC` needs authentication
`OPTIONS /v1/sessions/` needs authentication

### Additional Information

This seems to be an issue with `io.micronaut.security.rules.InterceptUrlMapRule`, specifically this part:

```
        Optional<InterceptUrlMapPattern> matchedPattern = getPatternList()
                .stream()
                .filter(p -> p.getHttpMethod().map(method -> method.equals(httpMethod)).orElse(true))
                .filter(p -> pathMatcher.matches(p.getPattern(), path))
                .findFirst();
```

The assumption here seems to be, that patterns are unique. In my case the patterns are not unique, but the combination of patterns and httpMethods are.

### Environment Information

- **Operating System**: macOS Mojave 10.14.4
- **Micronaut Version:** 1.1.0.RC2 (Issue persists with 1.1.0.BUILD-SNAPSHOT)
- **JDK Version:** openjdk version "11.0.2" 2019-01-15
