### ISSUE TITLE
/caches endpoint throws NPE

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#1535]
The `/caches` endpoint throws NullPointerException.

I traced it down to line 205 in DefaultSyncCache.java. The `eviction` variable is null and dereferenced without a check.

```
        Policy policy = caffeineCache.policy();
        Policy.Eviction eviction = (Policy.Eviction) policy.eviction().orElse(null);
        Policy.Expiration expireAfterAccess = (Policy.Expiration) policy.expireAfterAccess().orElse(null);
        Policy.Expiration expireAfterWrite = (Policy.Expiration) policy.expireAfterWrite().orElse(null);
        Long maximumSize = (!eviction.isWeighted() ? eviction.getMaximum() : null);
```

I'm still trying to figure out why this is happening and if something is wrong with my configuration.

### Steps to Reproduce

Configure a cache in application.yml
```
micronaut:
    caches:
        my-cache:
            initialCapacity: 100
            maximumSize: 1000
            expireAfterAccess: 10m
endpoints:
    caches:
        enabled: true
        sensitive: false
```
Try to access the caches endpoint.

`curl http://localhost:8080/caches`

### Expected Behaviour

The endpoint should return cache information.

### Actual Behaviour

```
java.lang.NullPointerException: null
        at io.micronaut.cache.DefaultSyncCache.getCaffeineCacheData(DefaultSyncCache.java:205)
        at io.micronaut.cache.DefaultSyncCache.access$200(DefaultSyncCache.java:50)
        at io.micronaut.cache.DefaultSyncCache$1.get(DefaultSyncCache.java:102)
        at io.micronaut.management.endpoint.caches.CachesEndpoint.lambda$getCaches$1(CachesEndpoint.java:72)
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.1.0
- **JDK Version:**  1.8.0_162

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
@goeh I can't reproduce the issue. Please upload a sample app

**Comment by jameskleeh** [comment]
I can reproduce the issue if I remove `maximumSize` and `expireAfterAccess` from config

**Comment by goeh** [comment]
I found the source of the problem. It was not **my** cache that caused the NPE. It was the "discovery-client" cache that is created by the Eureka integration. That cache is not fully configured and caused the /caches endpoint to NPE. Thanks for the fix!

**Comment by goeh** [comment]
Workaround for Micronaut 1.1.0 with service discovery enabled. Configure the "discovery-client" cache in application.yml to make /caches endpoint not throw NPE.
```
micronaut:
    caches:
        discovery-client:
            initialCapacity: 5
            maximumSize: 100
            expireAfterWrite: 30s
            expireAfterAccess: 30s
            recordStats: true
```
