### ISSUE TITLE
Improve the documentation for using multiple JDBC data sources/persistence contexts

### ISSUE THREAD

**Issue by knyttl** [micronaut-projects/micronaut-core#1628]
### Current state

- There is an example for using Hibernate within a project: https://guides.micronaut.io/micronaut-data-access-jpa-hibernate/guide/index.html
- Docs mentions @PersistenceContext with qualifier here: https://docs.micronaut.io/1.0.0.M4/guide/index.html
```
@PersistenceContext
EntityManager entityManager;

@PersistenceContext(name = "other")
EntityManager otherManager;
```

### The problem

When using persistence contexts, I expect it to be configured via application.yaml similarly to:

```
datasources:
  default:
    packages-to-scan:
      - 'my.package'
    url: ${JDBC_URL_MASTER}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}

  readOnly:
    packages-to-scan:
      - 'my.package'
    url: ${JDBC_URL_SLAVE}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}
```

Then I would expect to be able to access it via `@PersistenceContext`:

```
    @PersistenceContext(unitName = "readOnly")
    override lateinit var em: javax.persistence.EntityManager
```

### What happens

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [javax.persistence.EntityManager] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1825)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1346)
```

### What is expected to happen

I guess the docs are incomplete in this way and I haven't defined everything which should be. I should be able to inject the correct peristence context associated with defined dataSource.

**Comment by graemerocher** [comment]
Please try `read-only` instead of `readOnly`

**Comment by knyttl** [comment]
I replaced `readOnly` to `read-only` both in `application.yml` and in `unitName`, but with no effect.

**Comment by knyttl** [comment]
Note that application.yml defines datasource, not entitymanager.

**Comment by graemerocher** [comment]
Yeah the configuration is incorrect. `packages-to-scan` should be under `jpa`:

```yaml
jpa:
  default:
    packages-to-scan:
      - 'my.package'
  read-only:
    packages-to-scan:
      - 'my.package'
```
