### ISSUE TITLE
Specifying DATASOURCES_DEFAULT_USERNAME environment variable creates invalid datasource "default-username"

### ISSUE THREAD

**Issue by FylmTM** [micronaut-projects/micronaut-core#1831]
### Steps to Reproduce

1. Run application with `DATASOURCES_DEFAULT_USERNAME=postgres` environment variable
2. Request `/health` endpoint

Example application contains `README.md` with detailed steps on how to reproduce problem.

### Expected Behaviour

`DATASOURCES_DEFAULT_USERNAME` environment converted to `datasource.default.username` key, that overrides same key defined in `application.yaml`.

No additional side-effects should happen.

### Actual Behaviour

For environment variable `DATASOURCES_DEFAULT_USERNAME` property resolver is creating various combinations with `.` and `-` ([this micronaut test](https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy#L63) shows logic).

Because of this keys such as `datasources.default-username` are created.

When `/health` endpoint is requested it checks all configured datasources. Because of above key existence, micronaut considers that datasource with name `default-username` was configured.

But of course it's not, and and it does not contain valid configuration.

This leads to `/health` endpoint not behaving correctly (hangs).
Rest of application works normally.

In our case this leads to pod not being started correctly in Kubernetes cluster (it relies on successful health check).

### Current workaround

We are specifying our own environment variables in `application.yml`.

### Environment Information

- **Operating System**: Antergos Linux (Kernel 5.1.11-arch1-1-ARCH)
- **Micronaut Version:** 1.1.1
- **JDK Version:** openjdk version "11.0.4" 2019-07-16

### Example Application

- https://github.com/FylmTM/micronaut-issue-invalid-datasource

**Comment by graemerocher** [comment]
so the way you would do this is with

```yaml
datasources: 
     default:
         username: "${DB_USERNAME}"
```

And then set `DB_USERNAME` in your environment.

**Comment by jameskleeh** [comment]
You can also prevent that specific environment variable from being part of config at all by excluding it.

See this example in the docs:

```    public static void main(String[] args) {
        Micronaut.build(null)
                .mainClass(Application.class)
                .environmentPropertySource(false)
                //or
                .environmentVariableIncludes("THIS_ENV_ONLY")
                //or
                .environmentVariableExcludes("EXCLUDED_ENV")
                .start();
    }```

**Comment by FylmTM** [comment]
@graemerocher 

Well. This is exactly what we are doing today.

To be specific, this is our config:

```
datasources:
  default:
    url: ${APP_DATASOURCES_DEFAULT_URL:`jdbc:postgresql://localhost:5432/postgres?defaultSchema=my-app-schema`}
    username: ${APP_DATASOURCES_DEFAULT_USERNAME:postgres}
    password: ${APP_DATASOURCES_DEFAULT_PASSWORD:password}
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 2
```

We went with environment variables that we would use, if no datasources would be automatically created, just prefixing them with `APP_`.

Do you consider it realistic, to somehow fix problem with datasource being created?
If no - I am happy with this workaround and this issue can be considered closed.
