### ISSUE TITLE
Spring cloud config client not working 1.2.0RC2

### ISSUE THREAD

**Issue by Deviad** [micronaut-projects/micronaut-core#1981]
In 1.2.0RC2 (as per maven repository release)  the spring cloud config client does not work. It says it cannot find a configuration file. 
I am using the same configuration I have used for 1.1.4 which has given me no issues with that version.

```
micronaut:
    application:
        name: hello-world
    config-client:
        enabled: true
spring:
    cloud:
        config:
            enabled: true
            uri: http://localhost:8888/
            retry-attempts: 4 # optional, number of times to retry
            retry-delay: 2s # optional, delay between retries
```
https://github.com/Deviad/clarity/blob/feature/micronaut_eigth_attempt_120RC2/clarity-dispatcher/src/main/resources/bootstrap.yml
