### ISSUE TITLE
Declarative client doesn't apply basic authorization header from user in URL

### ISSUE THREAD

**Issue by larsduelfer** [micronaut-projects/micronaut-core#2000]
We tried to integrate a micronaut service with a spring cloud config server that is protected using basic authentication. 

Our bootstrap.yml looks like this:
```
micronaut:
  application:
    name: like-service
  config-client:
    enabled: true

spring:
  cloud:
    config:
      enabled: true
      uri: http://config:secret@localhost:10000
```
However, the username and password are not forwarded as http basic auth header. Is this not supported yet?
