### ISSUE TITLE
Allow Multi URL @Clients to be defined

### ISSUE THREAD

**Issue by calebvarberg** [micronaut-projects/micronaut-core#2079]
This is an enhancement request that would either allow for a single class definition with the @Client annotation to create multiple beans with differing base urls, or it would allow for a single client bean to have multiple directly accessible urls. Similar to how load balancing works, but provide a mechanism to choose which url to hit.

The configuration could look something like this

```
micronaut:
    http:
        services:
            testService:
                urls:
                    - key: shard1
                      url: http://url1.com
                    - key: shard2
                      url: http://url2.com
```

You would then be able to pass the key to the client somehow so that it knows what url to use. 

The basic problem I am running into is that I have data that is sharded across different regions and my service needs to be able to hit a specific shard depending on what data it needs to access. I would like to be able to do this by defining a single class instead of trying to define a class per shard as the sharding can change, and I would prefer not to have to make code changes to add a new shard.
