### ISSUE TITLE
v1.2.1 build fails on specifying OAuth2 client

### ISSUE THREAD

**Issue by adityasrini** [micronaut-projects/micronaut-core#2092]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Update build to stable release `1.2.1`
2. In `application.yml`, specify the following
```
oauth2:
      enabled: true
      clients:
        auth_zero:
          client-id: ${AUTH0_CLIENT_ID}
          client-secret: ${AUTH0_CLIENT_SECRET}
          openid:
            issuer: ${AUTH0_ISSUER}
```
3. Execute `./gradlew run`

### Expected Behaviour

Server starts up.

### Actual Behaviour

A stacktrace is produced and the build fails. [Link to Gist](https://gist.github.com/8f255e84a518811aa2ed642209eb7c71)

### Environment Information

- **Operating System**: macOS 10.14.6
- **Micronaut Version:** 1.2.1
- **JDK Version:** 12

### Example Application

- [Full application](https://gitlab.com/adityasrini/hsd-api/tree/debugging/micronaut121-build-failure-oauth)
