### ISSUE TITLE
Service's HttpClientConfiguration should inherit property values from default HttpClientConfiguration

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#2213]
Right now, when I have the following configuration:
```
micronaut:
  http:
    client:
      read-timeout: 60s
```
I expect that all services' Http clients are going to have timeout set to 60s, but there aren't.
