### ISSUE TITLE
MongoDB not localhost configuration

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#230]
Custom MongoDB configuration does not work for me:

```
mongodb:
  uri: "mongodb://user:password@12.345.67.890:27017"
```
or
```
mongodb:
  uri: "mongodb://12.345.67.890:27017"
  username: "user"
  password: "password"
```

error is
`Command failed with error 13: 'not authorized on user to execute command { count: "brands", query: {} }' on server xxx.xxx.xxx.xxx:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on user to execute command { count: \"brands\", query: {} }", "code" : 13, "codeName" : "Unauthorized" }`
