### ISSUE TITLE
@Client URI issue (Kubernates sample)

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#238]
My configuration is:
```
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>discovery-client</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
```

```
@Controller("/person")
public class PersonController implements PersonResource {
     // do some stuff here
}
```

```
@Client(id = "hello-world")
interface PersonClient extends PersonResource {
}
```

```
micronaut:
  application:
    name: hello-world
  server:
    port: 8081
```

`Env Var: HELLO_WORLD_SERVICE_HOST=127.0.0.1;HELLO_WORLD_SERVICE_PORT=8081`

```
public class PersonControllerTest {
    @RegisterExtension
    private PersonClient personClient = server.getApplicationContext().getBean(PersonClient.class);

     @Test
    void testHello() throws Exception {

        StepVerifier
                .create(personClient.getAll(Optional.empty()))
                .verifyComplete();
    }
}
```

**Result is**:
`java.lang.AssertionError: expectation "expectComplete" failed (expected: onComplete(); actual: onError(io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: no further information: /127.0.0.1:8081))`

**Also one more thing here**. How can I clarify for the `@Client ` that my `@Controller` path is `/person` ?

it seems that Discovery works fine. But client builds URL wrong way.
It should make: `http://` `host:post/controller-path`
It does: `http://` `/host:post`

**Comment by graemerocher** [comment]
Can you post your kubernetes deployment descriptor

**Comment by akozel** [comment]
I didnt deployed kubernetes. Just running app with env variable setting manually.

**Comment by graemerocher** [comment]
I tested deployment to kubernetes running in Docker (edge version with Kubernetes support). I found some other circumstances we were not taking into account, but deployment worked with the following docker compose:

```yaml
version: '3.3'
services:
  hello-frontend:
    build: hello-frontend/.
    depends_on:
      - hello-backend 
    image: kubernetes_hello-frontend
    ports:
      - "8080:8080"
  hello-backend:
    build: hello-backend/.
    image: kubernetes_hello-backend
    ports:
      - "8080"
    deploy:
      replicas: 2
```
