### ISSUE TITLE
StaticResourceResolver does not honor micronaut.server.context-path

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#2436]
### Task List

- [x ] Steps to reproduce provided
- [x ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add a server context-path in `application.yml`
```
micronaut:
  server:
    context-path: /mypath
```

2. Add a static route in `application.yml`
```
micronaut:
  router:
    static-resources:
      open-api-spec:
        paths: classpath:META-INT/swagger
        mapping: swagger/**
```
3. Try to access the route:
`http://localhost:8080/mypath/swagger/my-spec.yml` -> `404 NOT FOUND`
`http://localhost:8080/swagger/my-spec.yml` -> `200 OK`

### Expected Behaviour

The StaticResourceResolver should honor the context-path.

### Actual Behaviour

StaticResourceResolver does not honor `micronaut.server.context-path`

### Environment Information

- **Operating System**:  Windows 10
- **Micronaut Version:** 1.2.7
- **JDK Version:** jdk-13
