### ISSUE TITLE
[feature request] Configurable Netty event loop creation and sharing

### ISSUE THREAD

**Issue by bfg** [micronaut-projects/micronaut-core#2590]
Hey, 

I believe that well behaving micronaut application with controllers that return reactive types should be able to work entirely in one event loop group consisting of only one thread. Current situation is that each declarative http client/service creates it's own event loop group, http server creates acceptor group and worker group. This might be okay in most scenarios, but it does not allow to achieve maximum possible utilization of CPU cores due to context switching.

Therefore I propose that event loop creation gets moved away from http/grpc server to it's own `@Factory` class that would create event loops defined in configuration when they're needed; Http clients and servers should be able to reference event loop group by name in configuration and by default they should share `default` event loop. Event loop group configuration should also allow setting preference to use native event loop implementations (epoll/kqueue) and this requires changes implementations for obtaining socket/datagram channel classes in http/grpc client/server.

Example configuration:
```yaml
micronaut:
  netty:
   # netty event loop group config
    loops:
       # default, event loop group
       default:
         num-threads: 0 # 0 -> auto, number of cpu cores
         prefer-native-transport: true

      # some custom elg
      some-loop:
         num-threads: 1
         prefer-native-transport: false

  # http server config
  server:
    netty:
      event-loop-group: "default"  # use `default` netty ELG

  # http services
 http:
   services:
      my-service:
        event-loop-group: "some-loop" # use custom netty  ELG
```

Currently I'm stealing event loop group from http server on service startup with reflection to reuse it for other netty-based components; it works flawlessly, but the process of acquisition of netty event loop group is hackish and error-prone; it would be ideal to just inject event loop groups into my components; ability to provide event loop groups in factory classes would be awesome as well.

I'm willing to contribute code if project maintainers consider this as a sound proposition.
