### ISSUE TITLE
Add the possibility to not convert properties to kebab case

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#2681]
When  you want to add some data source properties (here for postgres) :
```yaml
datasources:
  default:
    url: jdbc:postgresql://localhost/mydb
    username: <username>
    password: <pwd>
    driver-class-name: org.postgresql.Driver
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000
    data-source-properties: { reWriteBatchInserts: true, disableColumnSanitiser: true }
```
The properties get re-written to kebab-case: `{re-write-batch-inserts=true, disable-column-sanitiser=true}`
So they become useless.

It would be nice to be able to declare to not process some properties.
