### ISSUE TITLE
Support random available port for management endpoints [Feature Request].

### ISSUE THREAD

**Issue by sollecitom** [micronaut-projects/micronaut-core#2686]
At the moment Micronaut management allows you to customize the port for the management endpoints.
The enhancement request is about allowing the following:

1. For property `endpoints.all.port` to specify value `-1`, with behaviour similar to when `-1` is passed as value to`micronaut.server.port`, to indicate a random available port.
2. For property `endpoints.all.port` to specify no value in application.yml to indicate defaulting to the value for `micronaut.server.port`. (At the moment this works if property `endpoints.all.port` doesn't appear at all in application.yml, but if it appears with empty value the startup fails).
3. For Micronaut to also log the management URI at startup, alongside the API URI.
---
So, for example:

2 different random available ports:
```
micronaut:
  server:
    port: -1
endpoints:
  all:
    port: -1
```
---
1 random available port for API, and management on that same port:
```
micronaut:
  server:
    port: -1
endpoints:
  all:
    port:
```
