### ISSUE TITLE
jasync-sql SSL configuration can't be just yaml

### ISSUE THREAD

**Issue by arudge** [micronaut-projects/micronaut-core#2705]
This came out of a conversation in the Gitter and it was suggested to created an issue for this to make it easier in the future

### Steps to Reproduce

1. attempt to configure a micronaut project to use jasync with ssl

### Expected Behaviour
Configuration as such would enable SSL connections to db:
```yaml
jasync:
  client:
    port: 5432
    host: 'localhost'
    database: 'ope-inbound-service'
    username: 'testusername'
    password: 'testpassword'
    maxActiveConnections: 5
    ssl: "enable"
```
See jasync-sql [SSLConfiguration](https://github.com/jasync-sql/jasync-sql/blob/master/db-async-common/src/main/java/com/github/jasync/sql/db/SSLConfiguration.kt#L21) modes that should be supported.

### Actual Behaviour

SSL connections are not enabled and rejected by Postgres.

### Solution/Work around
```kotlin
@Singleton
class SSLConfigurationTypeConverter : TypeConverter<String, SSLConfiguration> {

    override fun convert(
        source: String,
        targetType: Class<SSLConfiguration>,
        context: ConversionContext
    ): Optional<SSLConfiguration> {
        return when ((NameUtils.underscoreSeparate(source.toUpperCase(Locale.ENGLISH)))) {
            "REQUIRE" -> Optional.of(SSLConfiguration(SSLConfiguration.Mode.Require))
            else -> Optional.empty()
        }
    }
}
```
```kotlin
@Introspected(classes = [SSLConfiguration::class])
object Application {...
```

Another alternative to this would be to allow fully qualified `uri` connection strings.
