### ISSUE TITLE
Invalid type bound from @ConfigurationProperties

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#2958]
In `2.0.0.M1`.

I had the following configuration in yml:

```yaml
my:
  security:
    intercept-url-map:
      graphql:
        -
          pattern: /api/public/graphql
          access:
            - isAnonymous()
        -
          pattern: /api/public/graphiql
          access:
            - isAnonymous()
```

Which was intepreted by this bean:

```java
@ConfigurationProperties("my.security")
public class SecurityMapConfig {

	protected Map<String, List<BindableInterceptUrlMapPattern>> interceptUrlMap = new LinkedHashMap<>();

	public Map<String, List<BindableInterceptUrlMapPattern>> getInterceptUrlMap() {
		return interceptUrlMap;
	}

	public void setInterceptUrlMap(Map<String, List<BindableInterceptUrlMapPattern>> interceptUrlMap) {
		this.interceptUrlMap = interceptUrlMap;
	}

	public static class BindableInterceptUrlMapPattern {
		private String pattern;
		private List<String> access = new ArrayList<>();
		private HttpMethod httpMethod = null;

		public String getPattern() {
			return pattern;
		}

		public void setPattern(String pattern) {
			this.pattern = pattern;
		}

		public List<String> getAccess() {
			return access;
		}

		public void setAccess(List<String> access) {
			this.access = access;
		}

		public HttpMethod getHttpMethod() {
			return httpMethod;
		}

		public void setHttpMethod(HttpMethod httpMethod) {
			this.httpMethod = httpMethod;
		}

		public InterceptUrlMapPattern toInterceptUrlMapPattern() {
			return new InterceptUrlMapPattern(pattern, access, httpMethod);
		}
	}

}
```

This worked well in `1.3` but now in `2.0.0.M1` the value passed in `List` is not `BindableInterceptUrlMapPattern` but `LinkedHashMap`:

![image](https://user-images.githubusercontent.com/1880196/77225159-fccaa380-6b6c-11ea-81e7-d2d004de8e12.png)
