### ISSUE TITLE
RedisSession is not valid

### ISSUE THREAD

**Issue by tkec** [micronaut-projects/micronaut-core#312]
### Steps to Reproduce

1. 
dependency:
```
         <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>session</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.configuration</groupId>
            <artifactId>redis-lettuce</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>security</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>security-session</artifactId>
            <scope>compile</scope>
        </dependency>
```

application.yml
```
micronaut:
    application:
        name: micronaut-hello-world
    server:
        port: 8080
    session:
        http:
            redis:
                enabled: true
    security:
        enabled: true
        endpoints:
              login:
                  enabled: true
              logout:
                  enabled: true
        interceptUrlMap:
              -
                pattern: /hello
                access:
                  - isAnonymous()
              -
                pattern: /show
                access:
                  - isAuthenticated()
        session:
              enabled: true
              loginSuccessTargetUrl: /show
              loginFailureTargetUrl: /hello
              logoutTargetUrl: /hello

redis:
    uri: redis://localhost:6379
```

controller:
```
@Controller("/")
public class HelloController {

    @Get("/hello")
    public String hello() {
        return "hello world";
    }

    @Get("/show")
    public Map<String, String> show() {
        Map<String, String> map = new HashMap<>();
        map.put("a","a");
        map.put("b","b");
        return map;
    }
}
```

AuthenticationProvider:
```
@Singleton
public class AuthenticationProviderUserPassword implements AuthenticationProvider {
    private Logger logger = LoggerFactory.getLogger(AuthenticationProviderUserPassword.class);

    @Override
    public Publisher<AuthenticationResponse> authenticate(AuthenticationRequest authenticationRequest) {
        if ("username".equals(authenticationRequest.getIdentity())
                && "password".equals(authenticationRequest.getSecret())) {
            logger.info("authenticate succeed.");
            return Flowable.just(new UserDetails(authenticationRequest.getIdentity().toString(), new ArrayList<>()));
        }
        logger.info("authenticate failed.");
        return Flowable.just(new AuthenticationFailed());
    }
}
```
2. post http://localhost:8080/login with username and password

### Expected Behaviour

return /show controller result

### Actual Behaviour

return Http status 401

### Environment Information

- **Operating System**: Windows 7
- **Micronaut Version:** 1.0.0.M1
- **JDK Version:** Jdk8

I traced the source code and found that, when `SecurityFilter`  check whether request has been authenticated(attrbute named 'micronaut.AUTHENTICATION' in Session), `RedisSession.get` function in `io/micronaut/configuration/lettuce/session/RedisSessionStore.java` has some problem, the first line code `Optional<T> result = super.get(name, conversionContext);` return a not empty result, but type is a byte[], not required `UserDetails` class, So `SessionAuthenticationFetcher.fetchAuthentication` will return Flowable.empty(). I think because below code `super.get` does not use `valueSerializer` to deserialize, and the function will return immediately, the code `Optional<T> deserialized = valueSerializer.deserialize((byte[]) val, conversionContext.getArgument().getType());` does not to execute. 
```
@Override
        public <T> Optional<T> get(CharSequence name, ArgumentConversionContext<T> conversionContext) {
            Optional<T> result = super.get(name, conversionContext);
            if (!result.isPresent() && attributeMap.containsKey(name)) {
                Object val = attributeMap.get(name);
                if (val instanceof byte[]) {
                    Optional<T> deserialized = valueSerializer.deserialize((byte[]) val, conversionContext.getArgument().getType());
                    deserialized.ifPresent(t -> attributeMap.put(name, t));
                    return deserialized;
                }
            }
            return result;
        }
```
