### ISSUE TITLE
bootstrap.servers property seems to be broken with micronaut 2.0.0.M2

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-core#3210]
Since we upgraded to micronaut version 2.0.0.M2 (with micronaut-kafka 1.4.0) the configuration of the bootstrap.servers property seems to be broken.

During startup we get the error:

`The configuration 'bootstrap.servers[2]' was supplied but isn't a known config`

we get this message with varying indexes.

And the effect we see is also that if one broker of the kafka cluster is shut down the services using kafka will be busy for finding a connection to the cluster again. We guess that this has to do with the above config warning.

Our config looks like this (which worked before 2.0.0.M2)
```yml
kafka:
  bootstrap:
    servers:
      - server1.rhs.zz:9092
      - server2.rhs.zz:9092
      - server3.rhs.zz:9092
```
