### ISSUE TITLE
Serving SPAs

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-core#3496]
I think we could make serving SPAs simpler as it is common pattern to use Micronaut for API and bundle SPA frontend application as static resource.

My proposed solution is to extend `StaticResourceConfiguration` class with something like

```java
private boolean spa = false;
```

and extend `StaticResourceResolver` class with something like

```java
if (entry.getKey().isSpa()) {
    for (ResourceLoader loader : loaders) {
        Optional<URL> resource = loader.getResource(INDEX_PAGE);
        if (resource.isPresent()) {
            return resource;
        }
    }
}
```

under the end of loop finding available resource (`for (ResourceLoader loader : loaders)`).

Usage in `application.yml` would be:

```yaml
micronaut:
  router:
    static-resources:
      angular-frontend:
        paths: classpath:public/frontend
        mapping: /frontend/**
        spa: true
```

1. Would you like me to create PR?
2. Is naming it `spa` good? Maybe something like `fallback-to-index`?
