### ISSUE TITLE
Micronaut does not generate OpenAPI doc properly when using immutables

### ISSUE THREAD

**Issue by michellelian** [micronaut-projects/micronaut-core#3688]
When using Value.Immutable classes as the rest api request/response, the generated OpenAPI doc does not show the properties of the immutable class.

I asked the question in gitter and was advised to create an issue here.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. The Value.Immutable class:
```
@Value.Immutable
@JsonSerialize(as = ImmutableCity.class)
@JsonDeserialize(as = ImmutableCity.class)
@Introspected
@Schema(implementation = ImmutableCity.class, name = "City", description = "City model")
@Value.Style(
    get = {"is*", "get*"},
    init = "set*",
    passAnnotations = {Schema.class},
    visibility = ImplementationVisibility.PUBLIC)
public interface City {

    @JsonProperty("name")
    @NotBlank
    String getName();

    @JsonProperty("description")
    String getDescription();
}
```
2. The controller
```
@Controller("/city")
public class CityController {

    @Post("save")
    @Tag(name = "city")
    public HttpResponse<City> save(
        @Body City city) {
        // persist it...
        return HttpResponse.created(city);
    }
}
```
### Expected Behaviour
Expect the follow OpenAPI schema to be generated:
```
components:
  schemas:
    City:
      type: object
      description: City model
      properties:
        name:
          minLength: 1
          type: string
        description:
          type: string
```
### Actual Behaviour
The actual generated OpenAPI schema for `City` has no properties:
```
components:
  schemas:
    City:
      type: object
      description: City model
```

### Environment Information

- **Operating System**: macOs Catalina 10.15.5
- **Micronaut Version:** 1.3.5
- **JDK Version:** 1.8.0_181
