### ISSUE TITLE
Micronaut 2.x problem with JdbcRepository multiple data sources 

### ISSUE THREAD

**Issue by maryam-nikoukar** [micronaut-projects/micronaut-core#3723]
Hi, we are upgrading to Micronaut 2.x and we are having some issue on our data layer when using javax.transaction.Transactional annotation. We have two data sources on application.yml one for read only operations and one for read and write. 

```
datasources:
  main:
    pool-name: 'main-pool'
    url: 'the-url'
    username: 'username'
    password: 'password'
    dialect: POSTGRES
    driver-class-name: 'org.postgresql.Driver'
  read-only:
    pool-name: 'readonly-pool'
    url: 'the-url'
    username: 'username'
    password: 'password'
    dialect: POSTGRES
    driver-class-name: 'org.postgresql.Driver'
    read-only: true

```

 Our repos are annotated with io.micronaut.data.jdbc.annotation.JdbcRepository and also io.micronaut.data.annotation.Repository (with the name of the data source).

 ```
 @Repository("main")
@JdbcRepository(dialect = Dialect.POSTGRES)
public abstract class ReadWriterRepository 
        
         {


    @Transactional
    public Entity upsert(
            Entity entity) {
        ...
    }

 ```

 and 

 ```
@Repository("read-only")
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface ReaderRepository extends GenericRepository<E, ID>
       	 {}
 ```

The issue is when we can the method (upsert) annotaed with javax.transaction.Transactional and we are getting : "Multiple possible bean candidates found: [io.micronaut.transaction.jdbc.DataSourceTransactionManager, io.micronaut.transaction.jdbc.DataSourceTransactionManager]" . I was wondening if anyone has encoured the same issue and how to fix it? is there any incomatibility with micronaut data (1.1.1) and Micornaut 2.x?

When we debug in DefaultBeanContext.findConcreteCandidate there are two beans one for "ready-only" data source and one for "main" data source. before upgrading to Micronaut 2.x the data sources was automatically  picked up by io.micronaut.data.annotation.Repository("data-source-name"). and the transactional manager was automatically resolved to the correct bean
