### ISSUE TITLE
version 2.0.1 injection for Map<String, List<String>> test gives incorrect value

### ISSUE THREAD

**Issue by bhrt93** [micronaut-projects/micronaut-core#3956]
**application.yaml**
```
@Property( name ="Test")
private Map<String, List<String>> test;
In version 2.0.1 of Micronaut.
application.yaml
testmap:
  alpha:
    - 14
    - 25
  beta:
    - 23
    - 31
    - 23
  gamma:
    - 53
    - 13
    - 32
  delta:
    - 52
    - 10
    - 20
```

> Java code

Injecting Map of list generates incorrect map
Tried using Map of String
```
Property(name = "testmap")
private Map<String, List<String>> testmap;
```
Tried Map of Integer as well.
```
@Property(name = "testmap")
private Map<String, List<Integer>> testmap;
```
Value is injected incorrectly.
<img width="995" alt="Screenshot 2020-08-24 at 7 09 53 AM" src="https://user-images.githubusercontent.com/51748751/90995420-8f1e1a00-e5d9-11ea-9ec0-d260e8537fa0.png">
<img width="893" alt="Screenshot 2020-08-24 at 7 12 37 AM" src="https://user-images.githubusercontent.com/51748751/90995426-947b6480-e5d9-11ea-8d80-9a7758cf85d8.png">
