### ISSUE TITLE
Support division of readiness and liveness probes in /health endpoint

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4005]
Kubernetes supports both readiness and liveness probes, currently Micronaut's management module only really supports liveness.

We should add qualifiers to define health indicators as either `@Readiness` or `@Liveness` and define a selector on the health endpoint to expose these individually `/health` can continue to map to liveness.

Micronaut launch's `k8s.yml` should then be updated to point to the individual probes.

```yaml
         readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
```
