### ISSUE TITLE
Revise/alter NettyHttpServerConfiguration to remove ambiguous feature

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#4370]
Section [6.27.1 of the Micronaut docs](https://docs.micronaut.io/latest/guide/index.html#threadPools) describes using HttpServerConfiguration$Worker to configure thread pools (among other things). For example:

```
micronaut:
  server:
    netty:
      worker:
        num-threads: 10
```

However, this doesn't work as described. There is a bug such that the worker configuration only works if one specifies an event loop group that doesn't exist. For example:

```
micronaut:
  server:
    netty:
      worker:
        event-loop-group: foo
        num-threads: 10

```

The recommended approach is to just use Netty event loop groups and configure that, either using the default

```
micronaut:
  netty:
    event-loops:
      default:
        num-threads: 10
```

Or using the netty worker configuration to specified a named event loop group. For example.

```
micronaut:
  server:
    netty:
      worker:
        event-loop-group: foo
   netty:
     event-loops:
       foo:
         num-threads: 10
```

For the next major version of Micronaut, the ability to configure the worker directly – rather than via the default or a named event loop group – should be removed. This might be a breaking change for anyone who depends on the current behavior.
