### ISSUE TITLE
Add ability to manually declare services without requiring discovery server

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#468]
For Kubernetes or for external services that can't register with a discovery server it is useful to be able to manually declare them.

We should support this with:

```yaml
micronaut:
       http:
             services:
                    foo: http://foo
```

or multiple with load balancing:

```yaml
micronaut:
       http:
             services:
                    foo: 
                         - http://foo2
                         - http://foo2
```

Should then be possible to use `@Client("foo")` and DI an `HttpClient` named `foo`
