### ISSUE TITLE
Default Netty access log format causes warnings to be logged

### ISSUE THREAD

**Issue by sgrimm** [micronaut-projects/micronaut-core#4737]
### Steps to Reproduce

Add the following to `application.yml` with the Netty HTTP server configured:

```yaml
micronaut:
  server:
    netty:
      access-logger:
        enabled: true
```

Optionally add a log appender to `logback.xml` per the documentation, though that's not necessary to reproduce the problem.

### Expected Behaviour

The server starts up cleanly and logs requests to the access log in Common Log Format.

### Actual Behaviour

The server starts up, but logs two warning messages:

```
11:30:01.821 [main] WARN  i.m.h.s.n.h.a.e.AccessLogFormatParser - Unknown access log marker: %l
11:30:01.823 [main] WARN  i.m.h.s.n.h.a.e.AccessLogFormatParser - Unknown access log marker: %u
```

Access logging does appear to work and the two unknown markers are replaced with `-` so the bug report here is just about the warnings; warnings imply something is wrong with the system, which shouldn't happen when I use the default settings that the documentation says should be correct.

### Environment Information

- **Operating System**: OS X 10.15.7
- **Micronaut Version:** 2.2.0
- **JDK Version:** OpenJDK 15.0.1

**Comment by ross-holloway94** [comment]
Hello,

I'm not sure why this has been closed? This is still happening in version 2.3.0 .

The log format is declared in **AccessLogFormatParser** in micronaut-http-server-netty-2.3.0.jar .

It looks like a capital L is used for line number for logback, but u doesn't appear to be listed.
http://logback.qos.ch/manual/layouts.html

**Comment by gautamawekar** [comment]
@ross-holloway94  not sure if its acceptable to you, but you can give your own format e.g. `%h %r %s %b`

e.g.
```
micronaut:
  server:
    netty:
      access-logger:
        enabled: true
        loggerName: HTTP_ACCESS_LOGGER
        log-format: "%h %r %s %b"
```
