### ISSUE TITLE
Multiple @Scheduled(cron=) annotations never triggers

### ISSUE THREAD

**Issue by johndevs** [micronaut-projects/micronaut-core#4928]
### Steps to Reproduce

If you annotate a method with one `@Scheduled(cron=...)` annotation it triggers

If you annotate a method with multiple `@Scheduled(cron=...)` annotations none of them triggers

application.yml:
```
    executors:
      dispatcher:
        type: scheduled
        core-pool-size: 1
```

### Expected Behaviour

The method should get triggered when the cron expression matches one of the annoations

### Actual Behaviour

The method is never triggered when using multiple annotations

### Environment Information

- **Operating System**: Linux (running in docker)
- **Micronaut Version:** 1.2.0
- **JDK Version:** 15

### Example Application

- None available.
