### ISSUE TITLE
Question: How to invoke a function deployed to AWS from a test?

### ISSUE THREAD

**Issue by jexp** [micronaut-projects/micronaut-core#498]
How would I get access via a function client to a function deployed and running in aws?

If I just run the ApplicationContext and access the bean I get

```
io.micronaut.function.client.exceptions.FunctionNotFoundException: No function found for name: echo
    at io.micronaut.function.client.DefaultFunctionDiscoveryClient.getFunction(DefaultFunctionDiscoveryClient.java:77)
```

I deployed the function using the gradle function-aws plugin and can also execute it successfully from gradle via invoke.

I have a `~/.aws/credentials` and added to `application.yml`

```
micronaut:
    function:
        name: echo
aws:
    lambda:
        functions:
            echo:
                functionName: echo
    region: us-east-1
```

And my test looks like this:

```
@FunctionClient
public interface EchoClient {
    @Named("echo")
    Single<String> echo(String input);
}

public class EchoFunctionTest {
    @Test
    public void testFunction() throws Exception {
      try (ApplicationContext context = ApplicationContext.run()) { 
          EchoClient client = context.getBean(EchoClient.class); 
          assertEquals(client.echo("foo").blockingGet(), "foo foo");
     }
    }
}
```
