### ISSUE TITLE
Configurations properties are empty in native image

### ISSUE THREAD

**Issue by tomasrobertsson** [micronaut-projects/micronaut-core#5064]
### Issue
Nested configurations properties are empty in native image

### Steps to Reproduce
Create a structure of properties in yml configuration, alike:
```
mail:
  username: test
  users:
    - name: test
      value: 1
      colors:
        primary: red
        secondary: blue
        last: green
    - name: test2
      value: 2
      colors:
        primary: yallow
        secondary: orange
        last: okra
```

Map this to classes
```
@ConfigurationProperties("mail")
public class MailProps {
    private String username;
    private List<User> users;

    public String getUsername() { return username; }
    public void setUsername(String value) { this.username = value; }

    public List<User> getUsers() { return users; }
    public void setUsers(List<User> value) { this.users = value; }
}
public class User {
    private String name;
    private long value;
    private Colors colors;

    public String getName() { return name; }
    public void setName(String value) { this.name = value; }

    public long getValue() { return value; }
    public void setValue(long value) { this.value = value; }

    public Colors getColors() { return colors; }
    public void setColors(Colors value) { this.colors = value; }
}
public class Colors {
    private String primary;
    private String secondary;
    private String last;

    public String getPrimary() { return primary; }
    public void setPrimary(String value) { this.primary = value; }

    public String getSecondary() { return secondary; }
    public void setSecondary(String value) { this.secondary = value; }

    public String getLast() { return last; }
    public void setLast(String value) { this.last = value; }
}

```
I have also tried reducing the props to just the mail-class, with one property with same problem
### Expected Behaviour

If run in normal java netty environment the properties are correctly injected and populated

### Actual Behaviour

In native image the injected properties are empty

### Environment Information

- **Operating System**: Windows10 / (AWS Lambda)
- **Micronaut Version:** 2.3.3, 2.3.4
- **JDK Version:** Corretto-11.0.5.10.1
- **Native image:**  21.0.0.2

### Example Application

Your example application is one example:
https://github.com/micronaut-guides/micronaut-configuration
Run as JAVA - ok, as native image - no
