### ISSUE TITLE
Support directives separator when using YAML configuration

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-core#5099]
I think it would be great to be able to parse/understand directives separator so we can isolate the profiles in such way if possible — similar to what Spring Boot does.

I haven't found an option/setting within the YAML file to "activate" a profile/environment, so I guess that would be needed.

I understand this separation is already done when you have multiple files and we can look at the environment by the file name, but still, I think they are more clear if this is supported...again, if makes sense.

An example file would be like this:

```yaml
---
application:
  key: default
micronaut:
  application:
    name: kotlin-micronaut
  environment:
    active: default
  server:
    context-path: /api
    port: 8080
---
micronaut:
  config:
    activate:
      on-environment: development
  server:
    port: 9080
---
micronaut:
  config:
    activate:
      on-environment: test
  server:
    port: 9081
```

As you can see, the `server.port` was changed for the different environments, maintaining the rest of the configuration (common part) from `default`. As far as I can tell, that's how this works today when we have different files, this would only allow to have just one configuration file instead of multiple files. Not sure how much work might be needed...but it looks neat 😉
