### ISSUE TITLE
Properties names with numbers don't resolve correctly

### ISSUE THREAD

**Issue by furikake** [micronaut-projects/micronaut-core#5184]
### Steps to Reproduce

1. Create `application.yml` with 

```
aws:
  disable-ec2-metadata: disable-ec2-metadata value
  disable-ec2metadata: disable-ec2metadata value
  disable-ec-metadata: disable-ec-metadata value
  disable-ec2instance-metadata: disable-ec2instance-metadata value
```

2. Create Configuration class 

```
@ConfigurationProperties("aws")
public class AwsConfiguration {
    private String disableEc2Metadata;
    private String disableEcMetadata;
    private String disableEc2instanceMetadata;

// constructor, getters, and setters omitted
```

### Expected Behaviour

`disable-ec2-metadata value` should be returned by `awsConfiguration.getDisableEc2Metadata()`

### Actual Behaviour

`disable-ec2metadata value` is returned by `awsConfiguration.getDisableEc2Metadata()`

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.4.1
- **JDK Version:** AdoptOpenJDK jdk-16+36
