### ISSUE TITLE
How to get metrics in the Prometheus format?

### ISSUE THREAD

**Issue by Avbat** [micronaut-projects/micronaut-core#521]
How should I configure the Micronaut to get the `.../metrics` in the Prometheus format ?

Used: micronaut 1.0.0.M3

Now:
```
micronaut:
...
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true

```
and result: metrics name list
`{"names":["jvm.memory.max","executor.pool.size","executor.queued","executor.completed","jvm.gc.memory.promoted","jvm.memory.used", ..."]}`

I need to get: metrics in the prometheus format.

I tried all the options (Prometheus, Atlas etc) from the documentation page. `.../metrics` always returns a list of names.
