### ISSUE TITLE
Documentation error for aws.lambda.region

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#522]
Documentation says: 

```
----
aws:
    lambda:
        functions:
            hello:
                functionName: hello-world
                qualifer: foo
    region: us-east-1
----
```

However it should say: 

```
----
aws:
    lambda:
        functions:
            hello:
                functionName: hello-world
                qualifer: foo
        region: us-east-1
----
```

That it is to say key is `aws.lambda.region`
