### ISSUE TITLE
Can't configure JWT access token expiration

### ISSUE THREAD

**Issue by zmuzik** [micronaut-projects/micronaut-core#555]
Configuration value for JWT access token expiration is ignored.
application.yml:

```
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: somesecret
      defaultExpiration: 86400
```
Issued tokens expire in 3600 seconds (which is the default value mentioned in the docs  https://github.com/micronaut-projects/micronaut-core/blob/master/src/main/docs/guide/security/authenticationStrategies/jwt.adoc
 ) instead of 86400 seconds.

I'm using DelegatingAuthenticationProvider

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** OpenJDK 1.8.0_181
