### ISSUE TITLE
When registering with Eureka, Micronaut should retry a few times before shutting down

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#568]
### Steps to Reproduce

1. Add Eureka runtime dependency to build.gradle
    runtime "io.micronaut:discovery-client"
2. Add Eureka configuration to application.yml
```yaml
    eureka:
      client:
        registration:
          enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
```
3. Start Micronaut application before you start Eureka.

### Expected Behaviour

Micronaut should try to connect to Eureka a few times before shutting down (with configurable retries, timeouts and backoff).

When running services with docker-compose they all startup almost at the same time and it takes a while before all services are up and ready to receive requests. Configurable retries would help in that scenario.

### Actual Behaviour

The Micronaut application shuts down immediately if it cannot connect to Eureka.

```
ERROR i.m.d.registration.AutoRegistration - Error occurred during service registration with Eureka: Connect Error: Connection refused: eureka/172.22.0.5:8761
test-service-micronaut_1        | io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: eureka/172.22.0.5:8761
test-service-micronaut_1        | 	at io.micronaut.http.client.DefaultHttpClient.lambda$null$18(DefaultHttpClient.java:838)
...
INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

If I start Eureka, then wait 30 seconds for Eureka to initialize. Then start the Micronaut application, it registers with Eureka ok.

```
INFO  io.micronaut.runtime.Micronaut - Startup completed in 3774ms. Server Running: http://localhost:8091
test-service-micronaut_1        | 07:15:31.657 [nioEventLoopGroup-1-3] INFO  i.m.d.registration.AutoRegistration - Registered service [test-service-micronaut] with Eureka
```

### Environment Information

- **Operating System:** MacOS 10.13.6
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_162

### Example Application

- https://github.com/goeh/micronaut-issue-568

**Comment by graemerocher** [comment]
Micronaut already does this. See https://github.com/micronaut-projects/micronaut-core/blob/master/discovery-client/src/main/java/io/micronaut/discovery/eureka/client/v2/EurekaOperations.java#L46

The retry policy is configurable

**Comment by goeh** [comment]
Awesome! I was looking at the Eureka section in the user guide but now I see that retry-count is included in the Consul section.
https://docs.micronaut.io/latest/guide/index.html#_customizing_consul_service_registration

IMO the defaults (retry-count = 3, retry-delay=1s) are a little low.
Maybe you could add a paragraph in the user guide about these parameters and add the missing retry-delay.

**Comment by graemerocher** [comment]
Contributions welcome!

**Comment by goeh** [comment]
Confirmed. Retry settings works as expected.
```
eureka:
    client:
        registration:
            enabled: true
            fail-fast: false
            retry-count: 10
            retry-delay: 5s
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
```
