### ISSUE TITLE
static resource, security and intercept url map throws 401 if url parameters

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#578]
### Steps to Reproduce

Create an app: 

- `mn create-app example.micronaut`

Modify `application.yml`

```
micronaut:
    application:
        name: micronaut
    router:
        static:
            resources:
                enabled: true
                mapping: /**
                paths: classpath:public                
    security:
        enabled: true
        interceptUrlMap:
        -
            pattern: "/"
            httpMethod: GET
            access:
            - isAnonymous()
```

Put a `index.html` file in `src/main/resources/public`

```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Hello world</title>
</head>

<body>
Content of the document......
</body>

</html>
```
Create the next test: 

```
package example.micronaut;

import io.micronaut.context.ApplicationContext;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.uri.UriTemplate;
import io.micronaut.runtime.server.EmbeddedServer;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertNotNull;
import java.util.Map;
import java.util.HashMap;

public class IndexHtmlTest {

    private static EmbeddedServer server;
    private static HttpClient client;

    @BeforeClass
    public static void setupServer() {
        server = ApplicationContext.run(EmbeddedServer.class); 
        client = server
                .getApplicationContext()
                .createBean(HttpClient.class, server.getURL());  
    }

    @AfterClass
    public static void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (client != null) {
            client.stop();
        }
    }

    @Test
    public void testWithoutParams() {
        HttpRequest request = HttpRequest.GET("/");
        String body = client.toBlocking().retrieve(request);
        assertNotNull(body);
        assertTrue(body.contains("Hello world"));
    }

    @Test
    public void testWithParams() {

	String template = "/{?name}";
        Map<String, Object> arguments = new HashMap<>();
        arguments.put("name", "john");
        String uri = new UriTemplate(template).expand(arguments);
        HttpRequest request = HttpRequest.GET(uri);
        String body = client.toBlocking().retrieve(request);
        assertNotNull(body);
        assertTrue(body.contains("Hello world"));
    }
}
```
### Expected Behaviour

I expect both tests to pass

### Actual Behaviour

`testWithParams` fails. `io.micronaut.http.client.exceptions.HttpClientResponseException: Unauthorized`
is thrown. 

I've tried to set the intercept Url map to 
```

        interceptUrlMap:
        -
            pattern: "/{?name}"
            httpMethod: GET
            access:
            - isAnonymous()
```

but it does not work either.

### Environment Information

- **Operating System**: MacOs HighSierra
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:**  1.8.0_181
