### ISSUE TITLE
Proxy address fails w/ http URLs

### ISSUE THREAD

**Issue by rcanacci** [micronaut-projects/micronaut-core#5797]
When setting up a proxy for a given micronaut HttpClient, I tested using a full URL ('http://...') instead of an IP address or direct domain name (without http/https).

Example:

```
micronaut:
    http:
        services:
            vuln-db:
                url: ${myApp.baseUrl}
                proxy-type: HTTP                    
                proxy-address: 'http://www.my-app.com:80'
```

The application fails to start with a message saying the proxyAddress property cannot be found.

After changing to the IP address for the given domain, the proxyAddress setting worked and the proxy functioned as expected without issue.
