### ISSUE TITLE
Built-in endpoints not included in OpenApi generated yaml

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#638]
### Steps to Reproduce

1. Create an app `mn create-app example.micronaut.complete`
2. Add dependencies: 

```
    annotationProcessor "io.micronaut.configuration:openapi"
    compile "io.swagger.core.v3:swagger-annotations"
```

and `management` dependency

`compile 'io.micronaut:management'`

Annotate `Application.java`

````
package example.micronaut;

import io.micronaut.runtime.Micronaut;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;

@OpenAPIDefinition(
        info = @Info(
                title = "Hello World",
                version = "0.0",
                description = "My API",
                license = @License(name = "Apache 2.0", url = "http://foo.bar"),
                contact = @Contact(url = "http://gigantic-server.com", name = "Fred", email = "Fred@gigagantic-server.com")
        )
)
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}
````

Modify `application.yml`

```
micronaut:
    application:
        name: openapitutorial
    server:
        port: 8081
        cors:
            enabled: true
    router:
        static-resources:
            swagger:
                paths:
                    - classpath:META-INF/swagger
                mapping: "/swagger/**"
```

Create a test which verifies `/health` exists. 

```
package example.micronaut;

import io.micronaut.context.ApplicationContext;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.runtime.server.EmbeddedServer;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.Map;

public class HealthTest {

    private static EmbeddedServer server;
    private static HttpClient client;

    @BeforeClass
    public static void setupServer() {
        server = ApplicationContext.run(EmbeddedServer.class);
        client = server
                .getApplicationContext()
                .createBean(HttpClient.class, server.getURL());
    }

    @AfterClass
    public static void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (client != null) {
            client.stop();
        }
    }

    @Test
    public void testHealthRespondsOK()  {
        Map m = client.toBlocking().retrieve(HttpRequest.GET("/health"), Map.class);
        assertNotNull(m);
        assertTrue(m.containsKey("status"));
        assertEquals(m.get("status"), "UP");
    }
}
````

Create a test which verifies `/health` appears as an open api path.

````
package example.micronaut;

import io.micronaut.context.ApplicationContext;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.runtime.server.EmbeddedServer;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.yaml.snakeyaml.Yaml;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.Map;

public class OpenApiTest {

    private static EmbeddedServer server;
    private static HttpClient client;

    @BeforeClass
    public static void setupServer() {
        server = ApplicationContext.run(EmbeddedServer.class);
        client = server
                .getApplicationContext()
                .createBean(HttpClient.class, server.getURL());
    }

    @AfterClass
    public static void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (client != null) {
            client.stop();
        }
    }

    @Test
    public void testOpenApiContainsHealthEndpoint()  {
        String yamlString = client.toBlocking().retrieve(HttpRequest.GET("/swagger/hello-world-0.0.yml"), String.class);
        assertNotNull(yamlString);
        Yaml yaml = new Yaml();
        Map<String, Object> m = yaml.load(yamlString);
        assertNotNull(m);
        assertTrue(m.containsKey("paths"));
        assertTrue(m.get("paths") instanceof Map);
        assertTrue(((Map)m.get("paths")).containsKey("/health"));
    }
}
````

### Expected Behaviour

Test should pass

### Actual Behaviour

Test fails `assertTrue(((Map)m.get("paths")).containsKey("/health"));`

### Environment Information

- **Operating System**: MacOS HighSierra
- **Micronaut Version:** 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_181

### Sample app: 

https://github.com/micronaut-guides/micronaut-openapi

**Comment by graemerocher** [comment]
The `management` module would need to be compiled with the `openapi` module and then expose a `/swagger/management-1.0.yml` file if it was active.

In addition support would need to be added to process `@Endpoint` definitions

**Comment by ctoestreich** [comment]
The piece that I am most curious about is making sure that

```
micronaut:
    application:
        name: openapitutorial
    server:
        port: 8081
        cors:
            enabled: true
    router:
        static-resources:
            swagger:
                paths:
                    - classpath:META-INF/swagger
                mapping: "/swagger/**"
```

That static resources block portion ends up somewhere in the docs on how to expose your generated yaml.
