### ISSUE TITLE
Enhance jaeger tracing properties to allow propagation

### ISSUE THREAD

**Issue by jamescookie** [micronaut-projects/micronaut-core#6389]
### Feature description

Currently you can add `sender`, `reporter` and `sampler` properties for jaeger tracing, but you cannot add propagation. 
This means that if you want your micronaut service to take part in a distributed trace with another service using the default opentelemetry javaagent, you have to set an environment variable of `JAEGER_PROPAGATION: W3C` 
It would be good if the `io.micronaut.tracing.jaeger.JaegerConfiguration` class could be modified to take `CodecConfiguration` as well, something like:
```
tracing:
  jaeger:
    enabled: true
    codec:
       codecs: W3C
```
