### ISSUE TITLE
Security controller paths not included in generated open-api yaml

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#639]
### Steps to Reproduce

1. Create an app `mn create-app example.micronaut.complete`
2. Add dependencies: 

```
    annotationProcessor "io.micronaut.configuration:openapi"
    compile "io.swagger.core.v3:swagger-annotations"
```

and `security-jwt'` dependency

`compile 'io.micronaut:security-jwt'`

Annotate `Application.java`

````
package example.micronaut;

import io.micronaut.runtime.Micronaut;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;

@OpenAPIDefinition(
        info = @Info(
                title = "Hello World",
                version = "0.0",
                description = "My API",
                license = @License(name = "Apache 2.0", url = "http://foo.bar"),
                contact = @Contact(url = "http://gigantic-server.com", name = "Fred", email = "Fred@gigagantic-server.com")
        )
)
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}
````

Modify `application.yml` to enable security endpioints and whitelabel the swagger endpoint.

```
micronaut:
    application:
        name: openapitutorial
    server:
        port: 8081
        cors:
            enabled: true
    router:
        static-resources:
            swagger:
                paths:
                    - classpath:META-INF/swagger
                mapping: "/swagger/**"
    security:
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: pleaseChangeThisSecretForANewOne
        enabled: true
        interceptUrlMap:
            - 
                pattern: /swagger/*
                httpMethod: GET
                access:
                    - isAnonymous()
```

Create a test which verifies `/login` exists. 

```
package example.micronaut;

import io.micronaut.context.ApplicationContext;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.exceptions.HttpClientResponseException;
import io.micronaut.runtime.server.EmbeddedServer;
import io.micronaut.security.authentication.UsernamePasswordCredentials;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import static org.hamcrest.Matchers.hasProperty;
import static org.hamcrest.Matchers.is;


import java.util.Map;

public class LoginTest {

    private static EmbeddedServer server;
    private static HttpClient client;

    @BeforeClass
    public static void setupServer() {
        server = ApplicationContext.run(EmbeddedServer.class);
        client = server
                .getApplicationContext()
                .createBean(HttpClient.class, server.getURL());
    }

    @AfterClass
    public static void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (client != null) {
            client.stop();
        }
    }

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Test
    public void testLoginEndointExists() {
        thrown.expect(HttpClientResponseException.class);
        thrown.expect(hasProperty("response", hasProperty("status", is(HttpStatus.BAD_REQUEST))));
        client.toBlocking().exchange(HttpRequest.POST("/login", new UsernamePasswordCredentials()), String.class);
    }
}
````

Create a test which verifies `/login` appears as an open api path.

````
package example.micronaut;

import io.micronaut.context.ApplicationContext;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.runtime.server.EmbeddedServer;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.yaml.snakeyaml.Yaml;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.Map;

public class OpenApiTest {

    private static EmbeddedServer server;
    private static HttpClient client;

    @BeforeClass
    public static void setupServer() {
        server = ApplicationContext.run(EmbeddedServer.class);
        client = server
                .getApplicationContext()
                .createBean(HttpClient.class, server.getURL());
    }

    @AfterClass
    public static void stopServer() {
        if (server != null) {
            server.stop();
        }
        if (client != null) {
            client.stop();
        }
    }

    @Test
    public void testOpenApiContainsLoginEndpoint()  {
        String yamlString = client.toBlocking().retrieve(HttpRequest.GET("/swagger/hello-world-0.0.yml"), String.class);
        assertNotNull(yamlString);
        Yaml yaml = new Yaml();
        Map<String, Object> m = yaml.load(yamlString);
        assertNotNull(m);
        assertTrue(m.containsKey("paths"));
        assertTrue(m.get("paths") instanceof Map);
        assertTrue(((Map)m.get("paths")).containsKey("/login"));
    }
}
````

### Expected Behaviour

Test should pass

### Actual Behaviour

Test fails `assertTrue(((Map)m.get("paths")).containsKey("/login"));`

### Environment Information

- **Operating System**: MacOS HighSierra
- **Micronaut Version:** 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_181

### Sample app: 

https://github.com/micronaut-guides/micronaut-openapi
