### ISSUE TITLE
ConfigurationProperties breaks with env variables with digits

### ISSUE THREAD

**Issue by brandonlamb** [micronaut-projects/micronaut-core#645]
Thanks for reporting an issue for Micronaut, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (http://stackoverflow.com/tags/micronaut) or Gitter (https://gitter.im/micronautfw/). DO NOT use the issue tracker to ask questions.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a config model/class using `ConfigurationProperties`
1. Configure `application.yml` to reference an environment variable containing a number (e.g. `DB2_USER`

### Expected Behavior

The configuration should be parsed correctly from environment variables even when containing numbers.

### Actual Behavior

Application fails to run. The regex for matching seems to exclude digits for some reason? Simply removing the `2` from environment variable names works.

### Environment Information

- **Operating System**: Docker
- **Micronaut Version:** 1.0.0-M4
- **JDK Version:** adoptopenjdk/openjdk10-openj9:jdk-10.0.2.13_openj9-0.9.0-alpine-slim

### Example Application

```kotlin
@ConfigurationProperties("app.db.db2")
class DbConfig {
  lateinit var url: String
  lateinit var user: String
  lateinit var pass: String
  lateinit var driver: String
}
```

```yaml
---
micronaut:
  application:
    name: my-app-v1
  server:
    port: ${HTTP_PORT:8080}

---
app:
  db:
    db2:
      user: ${DB2_USER}
      pass: ${DB2_PASS}
      url: ${DB2_URL}
      driver: ${DB2_DRIVER:com.ibm.db2.jcc.DB2Driver}
```
