### ISSUE TITLE
Method not allowed is returned for static resources if there is another endpoint with different http method

### ISSUE THREAD

**Issue by segocago** [micronaut-projects/micronaut-core#6580]
### Expected Behavior

Get requests to static resources should not be returning method not allowed if there is another http method that maps to request. Router should check if there are static resources before returning error response.

### Actual Behaviour

A method not allowed response with available methods is returned instead of the static resource.

### Steps To Reproduce

1. Using micronaut 3.1.3
2. Serve some static resources in /test path with following config in application.yml
```
micronaut:
  router:
    static-resources:
      my-static-resource:
        paths: <path_to_static_resource>
        mapping: /my-static-resource/**
```
3.Create a controller with a different http method than GET.
```
@Controller("/")
public class OptionsController {

  @Options("/my-static-resource")
  void handleOptions() {
    
  }
}
```

With the above configuration, requests to /my-static-resource return Method Not Allowed with allow: Options header instead of the actual resource.
### Environment Information

- OS: MacOs 11.6
- JDK: 17

### Version

3.1.3
