### ISSUE TITLE
Add option to escape `${looks-like-a-variable}` in application.yml

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#6783]
### Feature description

Right now there is no option to escape a value in an `application.yml` file that looks like a variable, so micronaut won't try to resolve it.

Below is my simplified use case. I want to write variables to an `.env` file with content from an  `application.yml`.

Example `application.yml`
```yml
my-section:
  var: ${looks-like-a-variable}
```

Example service (groovy) that writes the `.env` file.

```groovy
@Singleton
class Test {
    
    final protected String myVar
    
    Test(@Value('${my-section.var}') String myVar) {
        this.myVar = myVar
    }
    
    void writeShellScript() {
        new File(".env").text = """TEST=${myVar}
        """
    } 
}
```

**Comment by timyates** [comment]
As a workaround, I believe you can do:

```
my-section:
  var: ${:$}{looks-like-a-variable}
```

**Comment by jchanaud** [comment]
Another workaround we use, as suggested by @jameskleeh on Gitter few months ago : 
````yaml
micronaut:
  application:
    name: aes256VaultApi
# hack to avoid triggering PropertyPlaceholderResolver
# otherwise "${aes256:%s}" would always result as "%s"
dollar: '$'
vaults:
  test:
    key: aaaabbbbccccdddd
    salt: p8t42EhY9z2eSUdpGeq7HX7RboMrsJAhUnu3EEJJVS
    format: ${dollar}{aes256:%s}
````
