### ISSUE TITLE
Host resolution (X-Forward-Headers) has no effect

### ISSUE THREAD

**Issue by StefanKreidel** [micronaut-projects/micronaut-core#6905]
### Expected Behavior

I am running a Micronaut service behind a Traefik ingress controller (reverse proxy) which strips each URL of a base-path and omits https.
I want to make use of the `host-resolution` properties to rewrite all URLs according to the X-Forward-Headers which Traefik thankfully provides.

I expect Micronaut / Netty to rewrite all URLs (e.g. for Swapper/OpenAPI) accordingly.

Requested sent by browser: `https://some.domain/base-path/rest-resource`
Request sent by Traefik: `http://internal.domain/rest-resource` (different protocol, domain and missing base-path)
URLs created by Micronaut / Netty should be rewritten according to the headers Traefik provides.

### Actual Behaviour

I can verify that a `DefaultHttpHostResolver` bean with the appropriate `host-resolution` properties exists. However, it has no effect on the URLs generated by Micronaut / Netty.

![forward-headers-exception](https://user-images.githubusercontent.com/65711902/153557798-ae51afe8-234e-4c80-a983-eb434e03227a.png)

Here you can see that the application runs behind the base-path `pi-backend-pr-3`. The self-link href does however not include the base-path.

![forward-headers-swagger](https://user-images.githubusercontent.com/65711902/153558000-0ede01dd-ef30-42a5-9d27-1c8edcdca7d4.png)

Same for OpenAPI / Swagger integration. It tries to load the API documentation without the base-path. Also, if I temporarily correct this by entering the correct relative URL, the API documentation loads correctly. But then tryouts do not work because the URLs are once again missing the base-path.
Interestingly, the protocol is set correctly for tryout request. As explained, Traefik omits https in favor of http communication inside our infrastructure but sets the `X-Forwarded-Proto`. This is somehow picked up by Micronaut / Netty / OpenAPI.

I am not sure if I miss-configured or miss-understood something. Maybe there is something missing or maybe it is not working as intended. 
Any help, suggestions or insights would be much appreciated.

### Steps To Reproduce

application.yaml
```yaml
micronaut:
  server:
    host-resolution:
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
      host-header: X-Forwarded-Prefix
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```

build.gradle.kt
```gradle
kapt {
  arguments {
    arg("micronaut.openapi.views.spec", "redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop")
  }
}

dependencies {
  kapt("io.micronaut.openapi:micronaut-openapi")
  implementation("io.swagger.core.v3:swagger-annotations")
  // ...
}
```

### Version

3.3.0

**Comment by yawkat** [comment]
The `host-resolution` doesn't matter for path resolution. It really is only used for the resultion of the actual host.

Maybe you could get the behavior you want with a filter, or a pipeline customizer

**Comment by StefanKreidel** [comment]
Ah okay. It makes sense that it does not work then.
I'll try your suggestions and keep you updated!

**Comment by StefanKreidel** [comment]
I managed to solve my problem with a filter as described in the [documentation](https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#serverContext).

However, I think I found a better solution. Instead on relying on a `context-path` property which has to be available either during compile time or as system property during application startup, I parse the context-path from the request headers.

This allows for the same build artifact (jar) to be deployed on different stages / environments behind different reverse proxies which might serve different context-paths.
The only thing necessary for this to work is that the reverse proxy sets all the required headers. Here is my solution for the headers set by Traefik V2:

application.yaml
```yaml
micronaut:
  server:
    host-resolution:
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
      host-header: X-Forwarded-Host
      context-path-header: X-Forwarded-Prefix
```

HttpFilter (Kotlin code)
```Kotlin
import io.micronaut.context.annotation.Requires
import io.micronaut.context.annotation.Value
import io.micronaut.core.async.publisher.Publishers
import io.micronaut.http.HttpMethod.GET
import io.micronaut.http.HttpMethod.HEAD
import io.micronaut.http.HttpRequest
import io.micronaut.http.MutableHttpResponse
import io.micronaut.http.annotation.Filter
import io.micronaut.http.cookie.Cookie
import io.micronaut.http.filter.HttpServerFilter
import io.micronaut.http.filter.ServerFilterChain
import org.reactivestreams.Publisher
import java.time.Duration

@Filter(
	methods = [GET, HEAD],
	patterns = ["/**/rapidoc*", "/**/redoc*", "/**/swagger-ui*"]
)
@Requires(property = "micronaut.server.host-resolution.context-path-header")
class OpenApiBasePathFilter(
	@Value("\${micronaut.server.host-resolution.context-path-header}") private val contextPathHeader: String
) : HttpServerFilter {

	override fun doFilter(
		request: HttpRequest<*>,
		chain: ServerFilterChain
	): Publisher<MutableHttpResponse<*>> {
		val contextPath = request.headers[contextPathHeader] // case-insensitive lookup

		return if (contextPath != null) {
			val basePathCookie = Cookie.of("contextPath", contextPath).maxAge(Duration.ofMinutes(10L))
			Publishers.map(chain.proceed(request)) { response -> response.cookie(basePathCookie) }
		} else {
			chain.proceed(request)
		}
	}

}
```

@yawkat maybe this solution should be added to the documentation? Mainly because that's how Spring works and I presume that most people are used to it this way. I'm happy to open a PR if you think so as well.
