### ISSUE TITLE
UPPERCASE hostname registered in Eureka

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#710]
I have a system with Eureka, Spring Cloud Gateway and a handfull of Micronaut microservices behind the gateway.
When I try to access a service via the gateway I get `java.net.UnknownHostException: UPPERCASE-HOSTNAME`.
If I look at how services are registered with Eureka and I compare a Spring service with a Micronaut service I can see the difference.

Spring Service
```
    <name>GR8CRM-ACCOUNT-SERVICE</name>
    <instance>
      <instanceId>db87e7cc2278:gr8crm-account-service:8088</instanceId>
      <hostName>db87e7cc2278</hostName>
      <app>GR8CRM-ACCOUNT-SERVICE</app>
      <ipAddr>172.18.0.9</ipAddr>
      <status>UP</status>
      <overriddenstatus>UNKNOWN</overriddenstatus>
      <port enabled="true">8088</port>
      <securePort enabled="false">443</securePort>
      <countryId>1</countryId>
      <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
        <name>MyOwn</name>
      </dataCenterInfo>
```
Micronaut service
```
    <name>GR8CRM-NOTIFICATION-SERVICE</name>
    <instance>
      <instanceId>gr8crm-notification-service:8084</instanceId>
      <hostName>GR8CRM-NOTIFICATION-SERVICE</hostName>
      <app>GR8CRM-NOTIFICATION-SERVICE</app>
      <ipAddr>172.18.0.10</ipAddr>
      <status>UP</status>
      <overriddenstatus>UNKNOWN</overriddenstatus>
      <port enabled="true">8084</port>
      <securePort enabled="false">0</securePort>
      <countryId>1</countryId>
      <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
        <name>MyOwn</name>
      </dataCenterInfo>
```
**The hostName value is UPPERCASE**.

In my `docker-compose.yml` i have set MICRONAUT_SERVER_HOST to a lowercase name, but it gets converted to uppercase in Eureka.
```yml
  gr8crm-notification-service:
    image: gr8crm-notification-service:1.0.0-SNAPSHOT
    environment:
      - EUREKA_HOST=gr8crm-registry-service
      - MICRONAUT_SERVER_HOST=gr8crm-notification-service
```

In Spring Cloud Gateway the Micronaut service route is configured like this:
```yml
      - id: gr8crm-notification-service
        uri: lb://gr8crm-notification-service
        predicates:
        - Path=/v1/notifications/**
```

### Steps to Reproduce

1. Start Eureka
2. Start a Micronaut service
3. Start Spring Cloud Gateway
4. Try to access the Micronaut service via the gateway

### Expected Behaviour

Possible to access Micronaut service through gateway.

### Actual Behaviour

In the Spring Cloud Gateway logyou can see java.net.UnknownHostException: UPPERCASE-HOSTNAME

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** master 2018-10-09
- **JDK Version:** 1.8.0_162-b12

### Example Application

- https://github.com/goeh/micronaut-health-issue

1. ./gradlew docker
2. docker-compose up
3. curl http://localhost:8761/eureka/apps | grep hostName

Hostname is all uppercase,
