### ISSUE TITLE
Allow disabling beans / packages via configuration

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#7169]
There are many situations in which a user may simply want to disable some beans in certain scenarios.

For the modules that we have built, we often make the configuration properties classes to implement [`Toggleable`](https://docs.micronaut.io/latest/api/io/micronaut/core/util/Toggleable.html) so that they can be enabled/disabled via configuration. In other places (such as other beans, or `package-info.java`) we use `@Requires` to make those beans conditional to the presence of some enabled configuration property, e.g.: `@Requires(property="some.configuration.enabled", value="true", defaultValue="true")`.

Unfortunately, not all configuration properties or bean definitions have those built-in requirements. Therefore, it would be great if there could be a global way to enable/disable beans or packages via configuration.

Proposal:

```yaml
micronaut:
  beans:
    disable:
      - com.mycompany.myapp.somepackage # Disables all beans in the com.mycompany.myapp.somepackage tree (including children).
      - com.mycompany.myapp.SomeClass # Disable all beans of that type.
```
