### ISSUE TITLE
Intermittent timeouts to /info in application deployed on OSE

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#719]
When deploying to OSE we are seeing intermittent timeouts when using the /info endpoint for liveness.  Several other boot and angular/node apps on the same cluster are not experiencing this behavior.  There is nothing abnormal in the stack trace and the timeout is set to 10s.

``` yaml
         livenessProbe:
            httpGet:
              path: /info
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 500
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /info
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
```

```
Version

OpenShift Master:
    v3.9.0+ba7faec-1 
Kubernetes Master:
    v1.9.1+a0ce1bc657 
OpenShift Web Console:
    v3.9.0+b600d46-dirty 
```

This seems hard to track down as the timeout blips so infrequently that manual loading of the endpoint, and other scripting seems reliable, but every so often this triggers a pod restart.  This is a POC application with 0 active users.  It is happening enough to be suspicious.

This isn't something that is easily trackable.  I will be switching the endpoint to something like / or /health to see if that experiences the same issues.

<img width="1214" alt="screen shot 2018-10-11 at 3 58 27 pm" src="https://user-images.githubusercontent.com/691357/46834069-fb8a2a00-cd6f-11e8-9655-e16c9da1e424.png">

<img width="574" alt="screen shot 2018-10-11 at 3 57 58 pm" src="https://user-images.githubusercontent.com/691357/46834070-fb8a2a00-cd6f-11e8-9913-ec24d094f36a.png">
