### ISSUE TITLE
Add flyway as managed dependency version

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-core#7225]
### Feature description

Gradle Version Catalogs is an amazing feature. The most amazing way to use it is with `micronaut-bom`, this is incredible, because can sync all Gradle plugins to managed Micronaut dependency versions. I can re-use protobuf and grpc versions from it and use it for initializing the Protobuf Gradle plugin. But I can't do the same thing for the flyway. I think it will be nice to add flyway as a managed dependency as well. It will allow syncing the Micronaut flyway version to the Gradle flyway plugin version.

**Comment by alvarosanchez** [comment]
Note that there is a [micronaut-flyway-bom](https://search.maven.org/artifact/io.micronaut.flyway/micronaut-flyway-bom/5.2.0/pom)

**Comment by donbeave** [comment]
@alvarosanchez but there is no way to get flyway's version from it, the latest one has this content:

```toml
#
# This file has been generated by Gradle and is intended to be consumed by Gradle
#
[metadata]
format.version = "1.1"

[versions]
micronaut-flyway = "5.2.0"

[libraries]
micronaut-flyway = {group = "io.micronaut.flyway", name = "micronaut-flyway", version.ref = "micronaut-flyway" }
micronaut-flyway-bom = {group = "io.micronaut.flyway", name = "micronaut-flyway-bom", version.ref = "micronaut-flyway" }
```

source: https://repo1.maven.org/maven2/io/micronaut/flyway/micronaut-flyway-bom/5.2.0/micronaut-flyway-bom-5.2.0.toml
