### ISSUE TITLE
Enable finding eureka server via DNS entry

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#740]
Based on this documentation: there's way to find eureka via DNS registry. However, I couldn't find corresponding configs in `micronaut`

https://github.com/Netflix/eureka/blob/master/eureka-server/src/main/resources/eureka-client.properties

```
# If shouldUseDns is set to true, the below is an example of how to configure eureka client to route to eureka servers,
# assuming for example your DNS records are setup thus:
# txt record: txt.mycompany.eureka.mydomain.com => "server1address" "server2address" "server3address"
#eureka.shouldUseDns=true
#eureka.eurekaServer.domainName=mydomain.com
```

### Expected Behaviour

There should be a way to use DNS to find Eureka server.

### Actual Behaviour

No such configuration exists or is hard to find. I was pointed to here: https://github.com/micronaut-projects/micronaut-core/blob/master/discovery-client/src/main/java/io/micronaut/discovery/eureka/client/v2/InstanceInfo.java by @jameskleeh but this page doesn't have DNS related config or atleast wasn't obvious to me.

I could have totally missed something. Please correct me where I am wrong.

cc: @graemerocher 

P.S:  This is how we do it in our Spring Boot apps that register with Eureka:

```
eureka:
  instance:
    healthCheckUrlPath: /health
  client:
    region: global
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: eureka.storytel
    eurekaServerURLContext: eureka
    registerWithEureka: true
    fetchRegistry: true
```

**Comment by graemerocher** [comment]
@RaviH I don't see how this configuration is any different to doing:

```
eureka:
     client:
          defaultZone: http://eureka.storytel:8761
```

Or am I missing something?

**Comment by RaviH** [comment]
@graemerocher You could be absolutely right. I haven't tried. I don't know about DNS enough to know that `http://eureka.storytel:8761` would work. I will test and update here!

Thanks a lot @graemerocher.

**Comment by RaviH** [comment]
@graemerocher I checked and it doesn't work. I asked the DevOps and he said that `eureka.storytel` eventually gets resolved to: `http://eureka-us-east-1.eureka.storytel:8080`. Not sure how, still awaiting an answer from him. Thought I will update here.

So it seems to me that having same capability (as Netflix's eureka-client) for dns resolution in/with micronaut's eureka-client would be really helpful.

**Comment by graemerocher** [comment]
Thanks for the feedback, looks like we need to port https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/endpoint/EndpointUtils.java#L95

We will consider this after 1.0...

**Comment by graemerocher** [comment]
@RaviH I have added experimental support for this in master:

```yml
---
micronaut:
    application:
        name: eureka-test
        instance:
          zone: us-east-1
---
eureka:
  client:
    registration:
      enabled: true
    host: eureka.storytel
    should-use-dns: true
```

Let me know how you get on with it.
