### ISSUE TITLE
Improve @ConfigurationProperties

### ISSUE THREAD

**Issue by couragecowardlydog** [micronaut-projects/micronaut-core#7585]
### Feature description

Currently , for building complex objects from configuration i.e application.yml or a remote config server .

```
app:
  storage:
    location:
    filesytem:
    ..
    ..
  cdn:
    baseURL:
    ttl:
```

My Class would  look like
```
public class MyConfiguration{
    Storage storage:
    Cdn cdn;
}
```

With current state of @ConfigurationProperties , it expects me to write builder and then retrieve actual object from builder.
This looks pretty cumbersome,  from developer perspective, I would expect something simple and clean 

BTW Spring offers this :)

Ref: https://guides.micronaut.io/latest/micronaut-configuration-maven-kotlin.html
