### ISSUE TITLE
Frequent random 408 request timouts

### ISSUE THREAD

**Issue by deepsandeepme** [micronaut-projects/micronaut-core#7615]
### Expected Behavior

Expectation is to get the response from a dependent API call successfully without getting random frequent 408 request timeout.

Unfortunately, after enormous  failed attempts, I tried the traditional way and used io.micronaut.http.client.HttpClient to create the client manually and hit the dependent service. It resolved the issue.

I feel there is something with the configuration itself that is causing these timeouts.

### Actual Behaviour

I am trying to connect to external service using micronaut.security.auth2.clients. However, I am seeing frequent "408 request timeout" error. Initially, I though there might be a configuration issue. So, I went through the micronaut documentation and tried to set the micronaut.http.client.read-timeout: 30s. But, that did not work too. I still saw the request timeout. 

### Steps To Reproduce

In Any environment, 
1. Set up a security.auth2.client with token and auth method
```
micronaut:
  caches:
    devcaps:
      charset: 'UTF-8'
      expire-after-write: 60s
      expire-after-access: 60s
      maximum-size: 5
  security:
    oauth2:
      clients:
        auth0:
          client-id: ${app.client-id}
          client-secret: ${app.client-secret}
          grant-type: client_credentials
          client-credentials:
            service-id-regex: 'devcaps'
            scope: openid groups audience:server:client_id:${device-capabilities.client-id}
          token:
            url: ${app.token-gateway-url}
            auth-method: client_secret_post
```
2. Use @Client to configre the client and call the API.
3. Run the application in the kubernetes cluster
4. The integration works just fine when running in local machine

### Environment Information

- JDK Version: openjdk:11-jdk
- Azure AKS
- Micronaut 3.5.2

### Version

3.5.2
