### ISSUE TITLE
ConsulConfigurationClient doesn't use the ssl-configuration

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-core#7860]
### Expected Behavior

**GIVEN** the `consul.client.ssl-configuration`
```yaml
consul:
  client:
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
    config:
      format: yaml
      path: config/${CONSUL_KV_VERSION}/micronaut
    asl-token: ${CONSUL_ACL_TOKEN}
    secure: ${CONSUL_SECURE}
    ssl-configuration:
      enabled: ${CONSUL_SSL_ENABLED}
      protocol: ${CONSUL_SSL_PROTOCOL}
      trust-store:
        path: ${CONSUL_TRUSTSTORE_LOCATION}
        password: ${CONSUL_TRUSTSTORE_PASSWORD}
```
**THEN** we can access a secured consul requiring certificate

### Actual Behaviour

1. The `consul.client.ssl-configuration` is not taken into account into the generated `ConsulConfiguration` (using default one instantiate at field level)
2. Not sure, but I don't see where in `ConsulConfigurationClient` the ssl configuration is used when using `consulClient` to retrieve values

### Version

3.5.4
