### ISSUE TITLE
@Property annotation does not work in groovy

### ISSUE THREAD

**Issue by skorikovdm** [micronaut-projects/micronaut-core#791]
I am using Micronaut 1.0.0

My configuration (application.yml):

```
micronaut:
    application:
        name: config-test
app:
    param1: test1
    param2: test2
```

I wrote test service class in groovy:

```
@Singleton
class TestService {

    @Value('${app.param1}')
    String param1

    @Property(name = "app.param2")
    String param2

    @Property(name = "app")
    Map<String, String> params

    String test() {
        "param1 = ${param1}, param2 = ${param2}, params = ${params}"
    }
}
```

testService.test() output:
> param1 = test1, param2 = null, params = null

Same test service in Java produces:
> param1 = test1, param2 = test2, params = {param1=test1, param2=test2}

Link to github sample project: https://github.com/skorikovdm/micronaut-property-error
