### ISSUE TITLE
Extract BOM into its own project

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-core#8112]
Currently the BOM file is published alongside Micronaut Core, which has a number of issues. In particular, it makes it necessary to release a new version of Core if we want to publish bugfix releases of Micronaut which only include bugfixes of modules. It also makes it difficult to release pre-versions of Micronaut which depend on newer versions of modules.

I would therefore suggest to extract the BOM into its own module, for example `io.micronaut.platform:micronaut-platform` (to make it clear it's a platform and not just a BOM, e.g we publish a version catalog), or we could use `io.micronaut.bom:micronaut-bom` too.

Note that we could still publish a BOM alongside `micronaut-core` simply by importing the external BOM, but this could become a chicken and egg problem.

**Comment by sdelamo** [comment]
I think `io.micronaut.bom:micronaut-bom` will be clearer to users.

**Comment by melix** [comment]
https://github.com/micronaut-projects/micronaut-bom

**Comment by melix** [comment]
@sdelamo in which category do you think I should add `micronaut-bom` here? https://github.com/micronaut-projects/micronaut-docs-index/blob/main/modules.yml

**Comment by graemerocher** [comment]
"Build" probably

**Comment by melix** [comment]
So a few more questions (I will probably have more as I make progress):

- what version should we use? We can either version the BOM separately from core, which has the advantage that we could release new versions of the BOM _without_ having to release a new version of core. The problem with this is that the Gradle and Maven plugins wouldn't know which version of the BOM to use for a specific version of Micronaut. The other option is to align the version of the BOM with what we have in `core`. This means that for every release of "Micronaut", we need a release of the BOM which corresponds to the version of "core".
- what to do with "core" dependencies: currently the BOM contains dependencies from core as well as other Micronaut modules. We can either include such modules one by one, or by including their own BOMs. Does it mean we want to keep a "core" BOM in `micronaut-core`, which wouldn't be the "full" BOM, but a limited BOM with all the modules it provides?

**Comment by graemerocher** [comment]
A new module called micronaut-core-bom with just the core dependencies makes sense to me

**Comment by melix** [comment]
So more questions as expected. I am removing entries from the `micronaut-core` BOM (which would eventually become `core-bom`), by removing entries which are not used in the Micronaut Core project itself. This leaves us with a number of entries which could arguably go into the new BOM, or be left in the Core BOM.

For example, we have the following entries (truncated for example):

```toml
managed-gorm = { module = "org.grails:grails-datastore-core", version.ref = "managed-gorm" }
managed-graal = { module = "org.graalvm.nativeimage:svm", version.ref = "managed-graal-svm" }
managed-groovy = { module = "org.apache.groovy:groovy", version.ref = "managed-groovy" }
managed-h2 = { module = "com.h2database:h2", version.ref = "managed-h2" }
managed-jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "managed-jakarta-annotation-api" }
managed-jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "managed-jackson" }
managed-javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "managed-javax-annotation-api" }
managed-jcache = { module = "javax.cache:cache-api", version.ref = "managed-jcache" }
managed-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "managed-jsr305" }
managed-logback = { module = "ch.qos.logback:logback-classic", version.ref = "managed-logback" }
```

All those dependencies (and more) are managed _and_ directly used in the core build scripts. However, some should probably live in the new BOM (e.g `jakarta-annotation-api`).

But as soon as we do this, we are having a chicken and egg problem: if Micronaut Core depends on the Micronaut BOM, then it means that Micronaut BOM can only include _previous releases_ of Core. It also means that Core needs to depend on a _previous release_ of Micronaut BOM and therefore we break the fact that core and bom should have the same version.

If we make, say, core 4.0.0-SNAPSHOT depend on BOM 4.0.0-SNAPSHOT, and that we want to release 4.0.0, then what should we release first? If we release Core first, then core would depend on a SNAPSHOT version of BOM, which is wrong. But if we release BOM first, then BOM would depend on a SNAPSHOT version of core.

As a consequence, it seems that the only solution is that core _does not_ depend on the BOM at all. This raises questions for some dependencies which are used in the test scope (on other Micronaut projects for example).
