### ISSUE TITLE
Micronaut OpenAPI spec isn't generated correctly

### ISSUE THREAD

**Issue by bodiam** [micronaut-projects/micronaut-core#8383]
I've also posted this issue here: https://github.com/micronaut-projects/micronaut-openapi/issues/852, it seems I can't close/move this issue there, and I'm not sure what the root cause of this issue is. Sorry for reporting it twice!

### Expected Behavior

It seems the generation of OpenAPI specifications doesn't take [RFC-6570 URI template specification](https://tools.ietf.org/html/rfc6570) into account.

I have a method in Micronaut which looks like this:

`fun checkAvailability(availabilityRequest: AvailabilityRequest): Availability {`

My request looks like this:

```
data class AvailabilityRequest(
    val restaurantId: String,
    val partySize: Int,
    val visitTime: Instant,
)
```

However, I don't want to pass in a request, I'd like to pass in the individual parameters, such as:

`http://localhost/availability?restaurantId=1&partySize=2&visittime=whenever`

To do this, I annotated the controller method with this annotation:

`@Get("/{?availabilityRequest*}")`

(based on the info I found here: https://dzone.com/articles/micronaut-mastery-binding-request-parameters-to-po)

This works well, and all good. But now I want to generate an OpenAPI specification based on the above, and the generation doesn't seem to take the `?availabilityRequest*` into account. Instead, it still thinks the availabilityRequest is a parameter, which makes my mocks fail. 

The generated OpenAPI spec looks like this:

```
paths:
  /availability:
    get:
      tags:
      - availability
      summary: Availability check
      description: Returns the available timeslots
      operationId: checkAvailability
      parameters:
      - name: availabilityRequest
        in: query
        required: true
        explode: true
        schema:
          $ref: '#/components/schemas/AvailabilityRequest'
```

While I expected the OpenAPI spec to look more like this:

```
paths:
  /availability:
    get:
      tags:
      - availability
      summary: Availability check
      description: Returns the available timeslots
      operationId: checkAvailability
      parameters:
      - name: restaurantId
        in: query
        required: true
        schema:
          type: string
      - name: partySize
        in: query
        required: true
        schema:
          type: integer
          format: int32
```

### Actual Behaviour

See above

### Steps To Reproduce

Create a new app with a complex type as input for a Get method (maybe also Post?)
Enable openapi
Build the spec

### Environment Information

MacOS

### Version

3.7.4
