### ISSUE TITLE
Vault property not resolved anymore

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-core#8610]
### Expected Behavior

Properties exposed by a vault should be resolved. In `test-resources`, we have a test with the following configuration in `bootstrap.yml`:

```yaml
test-resources:
  containers:
    hashicorp-vault:
      path: 'secret/vault-test'
      secrets:
        - "micronaut.security.oauth2.clients.test.client-id=hello"
        - "micronaut.security.oauth2.clients.test.client-secret=world"
```

The secrets expose a `test` client, which is resolved in a test via:

```java
@Inject
    @Named("test")
    OauthClientConfiguration oauthClientConfiguration
```

This works in Micronaut 3.x, but fails with 4.0-SNAPSHOT.

### Actual Behaviour

Using Micronaut 4, the bean isn't resolved:

https://ge.micronaut.io/s/o7c5fr5vguiqu/tests/:test-resources-hashicorp-vault:test/io.micronaut.testresources.hashicorp.vault.VaultStartedTest/automatically%20starts%20a%20Vault%20container?focused-exception-line=0-2&top-execution=1

### Steps To Reproduce

Checkout https://github.com/micronaut-projects/micronaut-test-resources branch `cc/2.0.x` and run:

`./gradlew t-r-h-v:test --tests VaultStartedTest`

See the test fail.

### Version

4.0.0-SNAPSHOT
