### ISSUE TITLE
Sub map property resolution doesn't work as documented

### ISSUE THREAD

**Issue by 3mtee** [micronaut-projects/micronaut-core#8800]
### Expected Behavior

Per [documentation](https://docs.micronaut.io/latest/guide/#valueAnnotation)

>You can also use this feature to resolve sub maps. For example, consider the following configuration:
```yaml
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
```
>To resolve a flattened map containing only the properties starting with hibernate, use @Property, for example:
```java
@Property(name = "jpa.default.properties")
Map<String, String> jpaProperties;
```
>The injected map will contain the keys hibernate.hbm2ddl.auto and hibernate.show_sql and their values.

### Actual Behaviour

Property resolution produces an empty map.

If I change `jpaProperties`'s type to `Map<String, Object>` then I get the submap, but it contradicts  the documentation line

>The injected map will contain the keys `hibernate.hbm2ddl.auto` and `hibernate.show_sql` and their values.

### Steps To Reproduce

1. Create a new app by running `mn create-app hello-world`
2. Add properties to application.yaml:
    ```yaml
    jpa:
      default:
        properties:
          hibernate:
            hbm2ddl:
              auto: update
            show_sql: true
    ```
3. Create a bean:
    ```java
    @Context
    public class TestController {
        @Property(name = "jpa.default.properties")
        Map<String, String> jpaProperties;
    
        @PostConstruct
        public void setUp() {
            System.out.println(jpaProperties);
        }
    }
    ```
4. Run your app and check the console output, it should print an empty map `{}`

### Environment Information

- OS: macOS 13.2.1 (22D68)
- JDK: GraalVM CE 22.3.1 [17.0.6]

### Version

3.8.4
