### ISSUE TITLE
ServiceHttpClientConfiguration should use connectionPoolConfiguration from DefaultHttpClientConfiguration when not set

### ISSUE THREAD

**Issue by tom-rauk** [micronaut-projects/micronaut-core#8808]
### Expected Behavior

I would expect that connection pool configuration set at `micronaut.http.pool` would be used when not set at `http.services.*.pool`.

The folllowing code would always require pool configuration to be set for each service.

https://github.com/micronaut-projects/micronaut-core/blob/98f2638280b73ad786469c445c5aeb6760900926/http-client-core/src/main/java/io/micronaut/http/client/ServiceHttpClientConfiguration.java#L98

```
public ServiceHttpClientConfiguration(
            @Parameter String serviceId,
            @Nullable ServiceConnectionPoolConfiguration connectionPoolConfiguration,
            @Nullable ServiceSslClientConfiguration sslConfiguration,
            ApplicationConfiguration applicationConfiguration) {
        super(applicationConfiguration);
        this.serviceId = serviceId;
        if (sslConfiguration != null) {
            setSslConfiguration(sslConfiguration);
        }
        if (connectionPoolConfiguration != null) {
            this.connectionPoolConfiguration = connectionPoolConfiguration;
        } else {
            this.connectionPoolConfiguration = new ServiceConnectionPoolConfiguration();
        }
    }

```

### Actual Behaviour

Connection pool configuration set for DefaultHttpClientConfiguration is ignored when using ServiceHttpClientConfiguration.

In order to enable connection pooling configuration is required for each `service`.

### Steps To Reproduce

The following configuration will not leverage connection pooling for service `a-service`.

```
micronaut:
  http:
    client:
      pool:
        acquire-timeout: 500ms
        max-pending-acquires: 1000
        enabled: true
        max-connections: 5
    services:
      a-service:
        url: "http://localhost:5050"
        path: "/service"
```

### Environment Information

MacOS 13.1 (22C65)

### Version

3.8.5
