### ISSUE TITLE
Micronaut swagger ui not working with micronaut-security dependencies

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-core#8853]
### Expected Behavior

Swagger UI to work.

### Actual Behaviour

Swagger UI not working when micronaut security modules added as dependency.

### Steps To Reproduce

1. Created a simple app with micronaut jaxrs + swagger. **And Swagger UI Working at http://localhost:8080/swagger/views/swagger-ui**

2. Now Add micronaut security jwt dependencies. 
3. Try mvn mn:run and access swagger ui again. **Swagger ui not showing up.**

Seems some dependency conflict that prevents jaxrs swagger module getting registered. Hence UI not working. 

 

### Environment Information

JDK 11.

### Example Application

https://github.com/subash89/public-samples/tree/main/hellojaxrs

### Version

3.8.4

**Comment by graemerocher** [comment]
probably the UI is locked down and secured hence you can't access it?

**Comment by subash89** [comment]
@graemerocher  In the example application I provided, first thing I did was to get swagger UI working on a simple micronaut cli generated jaxrs project. And I can access the swagger UI without any issue. 

Then only thing I just did was add micronaut-security-jwt dependency and annotation processor to the pom. That's it. 
And swagger ui not showing up. 

In this reference project to reproduce the issue https://github.com/subash89/public-samples/tree/main/hellojaxrs
You can take out micronaut security dependency and its annotation processor. And swagger ui will come up without any issue on  http://localhost:8080/swagger/views/swagger-ui

**Comment by subash89** [comment]
@graemerocher  I just corrected https to http in swagger ui url, which was a typo to make sure if that's what you meant. Looks like a dependency conflict or one overpower the other. Any thoughts?

**Comment by subash89** [comment]
@graemerocher  I corrected something in steps to reproduce from "now" to "not" which I think is the one mislead you. My bad. So issue stands as originally in the subject and above comments.

**Comment by davidrtpereira** [comment]
I'm too this problem. Some return about this issue?

**Comment by FerroEduardo** [comment]
I was able to allow the access by defining these values, especially the `intercept-url-map`. The full source code can be found [here (application.yaml)](https://github.com/FerroEduardo/micronaut-todo/blob/main/src/main/resources/application.yaml)

```yaml
swagger-ui:
  enabled: true

micronaut:
  openapi:
    views:
      spec: rapidoc.enabled=true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
```

[Documentation about intercept-url-map](https://micronaut-projects.github.io/micronaut-security/1.2.0/guide/index.html#interceptUrlMap)

<details>
  <summary>Swagger UI working image</summary>
  
  ![image](https://github.com/micronaut-projects/micronaut-core/assets/47820549/322b4e27-432b-49da-99fb-af9d6128f0d2)
</details>
