### ISSUE TITLE
StaticResourceResolver doesn't work with context-path set.

### ISSUE THREAD

**Issue by elFarto** [micronaut-projects/micronaut-core#8948]
### Expected Behavior

StaticResourceResolver should work regardless if context-path is set or not.

### Actual Behaviour

StaticResourceResolver breaks if context-path is set.

### Steps To Reproduce

1. With this config:
```
micronaut:
  server:
    context-path: /app
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```
2. Then doing these requests:
http://localhost/app/swagger/swagger.yml -> 404
http://localhost/swagger/swagger.yml -> 302 (with a redirect to /app)

### Environment Information

- Windows
- Java17
- Undertow

### Version

3.8.5
