### ISSUE TITLE
micronaut.server.context-path not displaying in terminal

### ISSUE THREAD

**Issue by haaah** [micronaut-projects/micronaut-core#9161]
### Expected Behavior

```
micronaut:
  server:
    context-path: /document
    port: 8082

```
The expected display url within the terminal should be 
`http://localhost:8082/document`

### Actual Behaviour

The terminal shows only
`10:47:18.696 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2513ms. Server Running: http://localhost:8082`

The context path is working as intended when we access http://localhost:8082/document, this bug affect only the terminal display path

### Environment Information

Mac BigSur
Azul Zulu 18.0.1

### Version

3.9.0
