### ISSUE TITLE
New allowed-origins-regex property not working..?

### ISSUE THREAD

**Issue by steven-ww** [micronaut-projects/micronaut-core#9423]
### Expected Behavior

With 3.9.0 allowed-origins no longer supports a regex value for the cors configuration. Instead you now need to use a new property called allowed-origins-regex.

When replacing allowed-origins with allowed-origins-regex using the same regular expression and previously, it's expected that calls from an Origin matching the pattern are allowed through.

### Actual Behaviour

Calls with a matching Origin header are no longer accepted and a 403 forbidden is returned.

### Steps To Reproduce

Start a 3.8.9 micronaut server with a configuration set to 

```
micronaut:
    application:
        name: testApp
    server:
        cors:
            enabled: true
            configurations:
                web:
                    allowed-origins: 
                      - ^http(|s):\/\/(\w*\.)*integration\.mydomain\.com$
```

Make a call to an endpoint on that server specifying an Origin value in the header of "https://www.integration.mydomain.com"

You should receive a 200 okay.

Now change the configuration to the below and the version of Micronaut to 3.9.x
```
micronaut:
    application:
        name: testApp
    server:
        cors:
            enabled: true
            configurations:
                web:
                    allowed-origins-regex: ^http(|s):\/\/(\w*\.)*integration\.mydomain\.com$
```

Make the same call to an endpoint and you should receive a 403 Forbidden. (Expected that you receive a 200)

### Environment Information

macOS
JDK 17
Micronaut 3.8.9 and 3.9.2

### Version

3.9.2
