### ISSUE TITLE
Improve traceability of the JSON Property Binder in Micronaut 4.0

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#9577]
### Expected Behavior

Given the following YAML

```yaml
onstructive:
  product-engine:
    insurance-needs:
      insurance-needs: # <-- this collection causes troubles in Micronaut 4
        - key: insuranceNeeds.best.price
          id: bc14def2-07f9-4790-a5ba-4cea80d51d35
          products:
            - name: PRD_GV_BTC
            - name: PRD_ZV_SP3
            - name: PRD_KA_UTI
            - name: PRD_KA_KTI
              constraint:
                type: AGE
                range: "0..14"

    product-configuration:
      default-base-insurance-product: PRD_GV_BTC # Telmed
      third-kid-discount-code-active: COD_RK_BER
      third-kid-discount-code-inactive: COD_RK_NBE
      family-discount-code-active: COD_RK_MRA
      family-discount-code-inactive: COD_RK_ORA
      products: # <-- this collection causes troubles in Micronaut 4
        - name: PRD_KA_KTI # KTI
          insurance-begin-strategy: FIRST_DAY_OF_THE_FOLLOWING_YEAR_OR_NEXT_MONTH
          constraint:
            type: AGE
            range: "0..54"
          legal-basis: VVG
          criteria:
            - name: AGE_GROUP
              exposable: false
              constraint:
                type: AGE
                range: "0..0"
              value: COD_LA_B01
```

The immutable configuration should be bound correctly onto the `ConfigurationProperties` interface type.

### Actual Behaviour

For some reason, I do not understand yet, Micronaut has issues with binding collections onto the ProductConfiguration.

```java
@ConfigurationProperties(ProductConfiguration.PREFIX)
public interface ProductConfiguration {

  String PREFIX = ProductEngineConfiguration.PREFIX + ".product-configuration";

  @NotBlank
  String getDefaultBaseInsuranceProduct();

  @NotBlank
  String getThirdKidDiscountCodeActive();

  @NotBlank
  String getThirdKidDiscountCodeInactive();

  @NotBlank
  String getFamilyDiscountCodeActive();

  @NotBlank
  String getFamilyDiscountCodeInactive();

  Set<Product> getProducts();

  @Introspected
  record Product(
      String name,
      InsuranceBeginStrategy insuranceBeginStrategy,
      LegalBasis legalBasis,
      List<Criterion> criteria,
      Constraint constraint) {}

  // further code omitted... (see Git repo)
```

### Steps To Reproduce

1. Pull [this repository](https://github.com/saw303/m4configuration)
2. Checkout branch `micronaut394` and run `./gradlew check`. All tests will pass.
3. Checkout branch `micronaut400` and rerun the same Gradle task. Some tests will fail.

### Environment Information

- macOS Ventura
- JDK 17

### Example Application

https://github.com/saw303/m4configuration

### Version

4.0.0
