### ISSUE TITLE
ConfigurationProperties is not resolving property placeholders in a few places

### ISSUE THREAD

**Issue by cchandurkar** [micronaut-projects/micronaut-core#9609]
### Expected Behavior

It should resolve all the placeholders in nested objects. 

### Actual Behaviour

It only resolves property placeholders if the nested object is an "Array of Objects". But if it's just nested object, then it does not resolve. For example:

It works when `secrets` is an array of objects.
```
confluent:
  config:
    - name: events
      host: ${REGISTRY_HOST:}
      secrets:
        - api_key: ${REGISTRY_API_KEY:}
          api_secret: ${REGISTRY_API_SECRET:}
```

It does NOT work when `secrets` is just a nested object. 
```
confluent:
  config:
    - name: events
      host: ${REGISTRY_HOST:}
      secrets:
        api_key: ${REGISTRY_API_KEY:}
        api_secret: ${REGISTRY_API_SECRET:}
```

### Steps To Reproduce

Use this config
```yaml
confluent:
  config:
    - name: events
      host: ${REGISTRY_HOST:}
      kafka:
        secrets:
            api_key: ${REGISTRY_API_KEY:}
            api_secret: ${REGISTRY_API_SECRET:}
      secrets:
        - api_key: ${REGISTRY_API_KEY:}
          api_secret: ${REGISTRY_API_SECRET:}
```

and config class:
```
package example.micronaut.config;

import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.core.convert.format.MapFormat;
import io.micronaut.serde.annotation.Serdeable;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Getter
@Setter
@Serdeable
@ConfigurationProperties("confluent")
public class ConfluentConfiguration {

    private List<ConfluentConfig> config;

    @Getter
    @Setter
    @Serdeable
    public static class ConfluentConfig {
        private String name;
        private String host;
        private KafkaConfig kafka;
        private List<Map<String, String>> secrets = new ArrayList<>();
    }

    @Getter
    @Setter
    @Serdeable
    public static class KafkaConfig {
        @MapFormat(transformation = MapFormat.MapTransformation.FLAT)
        private Map<String, String> secrets = new HashMap<>();
    }
}
```
Refer to this [unit test](https://github.com/cchandurkar/micronaut-config-test/blob/main/src/test/java/example/micronaut/MicronautguideTest.java) in example [repo](https://github.com/cchandurkar/micronaut-config-test). My [config class](https://github.com/cchandurkar/micronaut-config-test/blob/main/src/main/java/example/micronaut/config/ConfluentConfiguration.java). 

### Environment Information

- MacOs
- JDK 17

### Example Application

https://github.com/cchandurkar/micronaut-config-test

### Version

3.9.4
