### ISSUE TITLE
@MapFormat keyFormat = RAW with @EachProperty injects empty map in some cases

### ISSUE THREAD

**Issue by Ksnz** [micronaut-projects/micronaut-core#9699]
### Expected Behavior

I have a configuration
```
some-property:
  working:
    string-value: "working"
    map-value:
      Injectable_Raw_Data:
        Foo: 4
        Foo_underscore: 2
  working-kebab-case:
    string-value: "working-kebab-case"
    map-value:
      Injectable_Raw_Data:
        Foo: 4
        Foo_underscore: 2
  not_working_underscore:
    string-value: "not_working_underscore"
    map-value:
      NotInjecrable_Raw_Data:
        Bar: 4
        Bar_underscore: 2
  notWorkingCamelCase:
    string-value: "notWorkingCamelCase"
    map-value:
      NotInjecrable_Raw_Data:
        Bar: 4
        Bar_underscore: 2
```
And corresponding class
```
@EachProperty("some-property")
public class SomeProperty {
    private String stringValue;
    private Map<String, Map<String, Double>> mapValue;

    public String getStringValue() {
        return stringValue;
    }

    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }

    public Map<String, Map<String, Double>> getMapValue() {
        return mapValue;
    }

    public void setMapValue(@MapFormat(keyFormat = StringConvention.RAW) Map<String, Map<String, Double>> mapValue) {
        this.mapValue = mapValue;
    }
}
```
I expect that `mapValue` is filled with data from  `map-value` property

### Actual Behaviour

When parent property key doesn't match kebab case and MapFormat set with keyFormat = RAW option it results into map with no data being injected.
So configurations named `not_working_underscore` and `notWorkingCamelCase` are resolved with empty map.

### Steps To Reproduce

1. Clone https://github.com/Ksnz/micronaut-bugs/tree/map-raw-bug
2. Run test or run and call `GET http://localhost:8080/hello`

### Example Application

https://github.com/Ksnz/micronaut-bugs/tree/map-raw-bug

### Version

3.9.5
