### ISSUE TITLE
@Property not working in kotlin

### ISSUE THREAD

**Issue by skorikovdm** [micronaut-projects/micronaut-core#971]
It seems that @Property is not working in Kotlin. I've created simple app with controller with two properties:
```kotlin
@Controller("/test")
open class TestController {

    @Property(name="app.string")
    var stringParam:String ?= null

    @Property(name="app.map")
    var mapParam:Map<String, String> ?= null

    @Get("/")
    fun index(): HttpResponse<String> {
        return HttpResponse.ok("""
            string param = ${stringParam}
            map param = ${mapParam}
            """).contentType(MediaType.TEXT_PLAIN_TYPE)
    }
```
my application.yml:
```yml
micronaut:
    application:
        name: kt-property
app:
    string: test1
    map:
        key1: value1
        key2: value2
```

Result of http://127.0.0.1:8080/test is
```
string param = null
map param = null
```
But when I've created the same controller in Java app, result was:
```
string param = test1
map param = {key1=value1, key2=value2}
```

### Environment Information
Micronaut 1.0.1, JDK 1.8

### Example Application
https://github.com/skorikovdm/kt-property
