### ISSUE TITLE
Openapi - Schema processing on the Application class level

### ISSUE THREAD

**Issue by lotfiZouad** [micronaut-projects/micronaut-core#982]
Currently, using a UUID in a controller method generates the following content in the swagger yml:
```
 UUID:
      type: object
      properties:
        leastSignificantBits:
          type: integer
          format: int64
          nullable: false
        mostSignificantBits:
          type: integer
          format: int64
          nullable: false
```

I would rather have:
```
UUID:
      type: string
      format: uuid
```

To avoid that, I have to use the schema annotation on parameters for every single controller method, it would be great to add the Schema processing on the Application class level like it's done for SecurityScheme and enrich the components/schemas section.
