### ISSUE TITLE
When security is enabled and using random port for endpoints.all.port even when health is senstive: false calling /health will result in 401

### ISSUE THREAD

**Issue by chenlin2001** [micronaut-projects/micronaut-core#9822]
### Expected Behavior

When using random port for endpoints.all.port the and conifguring
endpoints:
  all:
    port: -1
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    
  Calling /health should return correctly and not 401

### Actual Behaviour

When using:
```
micronaut:
  application:
    name: sample-application
  security:
    enabled: true

endpoints:
  all:
    port: 8081
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
``` 

I can run:
http://localhost:8081/health
And it returns ok

If I change it 
endpoints:
  all:
    port: -1
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
``` 

I get a 401 error:
{"_links":{"self":[{"href":"/","templated":false}]},"_embedded":{"errors":[{"message":"Unauthorized"}]},"message":"Unauthorized"}

### Steps To Reproduce

Following configuration in application.yml:

```
micronaut:
  application:
    name: sample-application
  security:
    enabled: true

endpoints:
  all:
    port: -1
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
``` 

Find the management port (can be done by putting a breakpoint in Micronaut.java and looking at embeddedServer.activeListeners()

and run: 
http://localhost:{managmentPort}/health

### Environment Information

Mac0S ventura 13.5
OpenJDK 17

### Example Application

_No response_

### Version

4.0.2

**Comment by pskowronek** [comment]
Still observing this behavior on Micronaut v4.9.4.

**Comment by pskowronek** [comment]
One workaround to have a random port and a proper `sensitivity` settings is to use: `${random.port}` directly in the configuration:

```
micronaut:
  application:
    name: sample-application
  security:
    enabled: true

endpoints:
  all:
    port: ${random.port} <---
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
```

This way it works as expected - logic behind works in the same way as if it was normal port configured.
The only problem imho is that it is slightly prone for race-conditions when multiple servers start in parallel (for example tests -> gradle parallel builds enabled). 

I've checked the documentation, and currently Micronaut documentation recommends to use `-1` for parallel tests: https://docs.micronaut.io/latest/guide/#runningSpecificPort

```
micronaut:
  server:
    port: -1
```

`Setting  an explicit port may cause tests to fail if multiple servers start  simultaneously on the same port. To prevent that, specify a random port  in the test environment configuration.`

However, here https://docs.micronaut.io/latest/guide/#propertySource in section "Using Random Properties"
there is the following property described: `random.port - An available random port number`. 

The questions are:
1) what is the recommended way of setting random port - using `-1` which is handled by Netty (system?) while binding to a port, or with `${random.port}`? 
2) if `${random.port}` is a recommended way, is it prone for a race condition if multiple servers start (parallel builds)?
3) if the logic responsible for setting an endpoint as sensitive or not (in https://github.com/micronaut-projects/micronaut-core/blob/5.0.x/management/src/main/java/io/micronaut/management/endpoint/EndpointsFilter.java ?), is using configuration value and not the real bound port number, then if think it looks like a security bug? I know that a chance that somebody was using `-1` (or `0` which `NettyHttpServer` treats alike) on production is low, but not zero. It of course depends if a default `sensitive` setting can be set to `false` - right now a default is `true` right?
