### ISSUE TITLE
Micronaut application won't start when including the logback dependency and configuring the log levels via application.properties

### ISSUE THREAD

**Issue by jaime-mugico** [micronaut-projects/micronaut-core#9835]
### Expected Behavior

The application start and set the right log level for the packages that have been specified in the application.properties file.

### Actual Behaviour

The application does not start due to the following error:
`
Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]

Message: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
Path Taken: new PropertiesLoggingLevelsConfigurer(Environment environment,List loggingSystems)
`

Debugging noticed that the latest `logback-classic` version (1.4.11) removed the method: `ContextInitializer.configureByResource`, but `LogbackUtils` from `micronaut-context:4.1.3` still uses it. 

### Steps To Reproduce

1. Create a micronaut service including logback dependency.
2. Configure the log level for a certain package using the application.properties like `logger.levels.com.example=DEBUG`
3. Try to run the application and it won't start.

It can also be reproduced just running the following test: https://github.com/jaime-mugico/micronaut-4.1.0-logback-context-bug/blob/main/src/test/kotlin/com/example/LogbackContextTest.kt#L9 that is included in the example application.

### Environment Information

- Operating system: macOS 13.5
- JDK: 1.17

### Example Application

https://github.com/jaime-mugico/micronaut-4.1.0-logback-context-bug/tree/main

### Version

4.1.0

**Comment by cimi** [comment]
I am seeing the same behaviour; it also reproduces when running `@MicronautTest`s if I have a logger configuration in `application-test.yml`.

I have everything configured via Gradle version catalog, using the logback and slf4j versions from the micronaut bom:

```toml
[versions]
micronaut = "4.1.0"

[libraries]
# ...
logback-classic = { module = "ch.qos.logback:logback-classic" }
# ...
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
# ...
slf4j-api = { module = "org.slf4j:slf4j-api" }
slf4j-jul = { module = "org.slf4j:jul-to-slf4j" }
```

**Comment by apankowski** [comment]
I'm observing the same issue. Just wanted to add the following for completeness:

Easiest reproducer:

1. Go to https://micronaut.io/launch/
2. Select Micronaut 4.1.0, `logback` and `yaml` features, Gradle or Gradle Kotlin, download ZIP
3. Unpack, add the following to `src/main/resources/application.yml`:
   ```yaml
   logger:
     levels:
       com.example: TRACE
   ```
4. Run `./gradlew test` for the startup to fail with stacktrace:
    ```
    Caused by: java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
        at io.micronaut.logging.impl.LogbackUtils.configure(LogbackUtils.java:103)
        at io.micronaut.logging.impl.LogbackUtils.configure(LogbackUtils.java:57)
        at io.micronaut.logging.impl.LogbackLoggingSystem.refresh(LogbackLoggingSystem.java:71)
    ```

As a workaround, add the following to `dependencies {}` block in `build.gradle.kts`:
```
dependencies {
    configurations.all {
        resolutionStrategy {
            force("ch.qos.logback:logback-classic:1.4.8")
            force("ch.qos.logback:logback-core:1.4.8")
        }
    }
}
```
This will force Logback dependencies to last version in which the method still existed. (This workaround passed a pretty sizeable test suite on a non-toy application after upgrading to Micronaut 4.1.0, so I feel pretty safe about it.)
