### ISSUE TITLE
JacksonConfigurations are ignored during JSONMediaTypeCodec

### ISSUE THREAD

**Issue by boates-rgare** [micronaut-projects/micronaut-core#9939]
### Expected Behavior

I want my application to send a JSON payload with java.util.Date properties written in date string format.

### Actual Behaviour

java.util.Date objects are being written as timestamps.

### Steps To Reproduce

Load the Grails Micronaut completed project OR any stable micronaut-http-client application with an api call with a json payload.

Put inside your application.yml:

```
jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.S'Z'"
    serialization:
        writeDatesAsTimestamps: false # other stack overflow documenation recommended us this field name
        write-dates-as-timestamps: false # autocomplete and documentation lead us to believe this was correct
```

Put a breakpoint at DefaultHttpClient ln 1351 so you can interrogate bodyContent after the codec does its work.
```
  Optional<MediaTypeCodec> registeredCodec = mediaTypeCodecRegistry.findCodec(requestContentType);
  bodyContent = registeredCodec.map(codec -> {
              if (bodyType != null && bodyType.isInstance(bodyValue)) {
                  return codec.encode((Argument<Object>) bodyType, bodyValue, byteBufferFactory).asNativeBuffer();
              } else {
                  return codec.encode(bodyValue, byteBufferFactory).asNativeBuffer();
              }
          })
          .orElse(null);
}
```

And another breakpoint at JacksonDatabindMapper ln 78
```
    @Internal
    public JacksonDatabindMapper() {
        this(new ObjectMapperFactory().objectMapper(null, null));
    }
```
    
 Then call your application so that it triggers the http-client with a request that contains an object to be JSON encoded.
 You should see the breakpoints be hit, showing that the JsonMediaTypeCode is using an object mapper that was created with a null JacksonConfiguration.  The result seems to be that we have no way to be modifying the behavior of the ObjectMapper user to json encode our outgoing payloads.
    

### Environment Information

macOs Ventura 13.6
JDK temurin 1.8
grailsGradlePluginVersion=5.3.0
grailsVersion=5.3.2
gormVersion=7.3.2
groovyVersion=3.0.13

Project had been migrated following this guide:
https://objectcomputing.com/files/5715/7841/1261/Slide_Deck_Grails_4_Upgrade_Webinar.pdf

    implementation 'io.micronaut:micronaut-http-client'

### Version

3.10
